# CSEC Principles of Accounts practice questions (p13-p100)
# Format: (question, [4 options], answer_index, explanation)
QUESTIONS = [
("The accounting equation is:", ["Assets = Liabilities + Capital", "Assets = Liabilities - Capital", "Capital = Assets + Liabilities", "Liabilities = Assets + Capital"], 0, "Assets are financed by liabilities and owner's capital."),
("If assets are $80,000 and liabilities are $25,000, the capital is:", ["$55,000", "$105,000", "$25,000", "$80,000"], 0, "Capital = Assets - Liabilities = 80,000 - 25,000 = 55,000."),
("Which of the following is a liability?", ["Bank loan", "Cash", "Inventory", "Equipment"], 0, "A loan is money owed to others."),
("An asset that is expected to be used for more than one year is a:", ["non-current asset", "current asset", "liability", "expense"], 0, "Non-current assets provide long-term benefit."),
("Which of the following is a current asset?", ["Accounts receivable", "Motor vehicle", "Land", "Buildings"], 0, "Receivables are converted to cash within a year."),
("The accounting concept that states a business is separate from its owner is:", ["business entity", "going concern", "prudence", "materiality"], 0, "The business entity concept separates business and personal affairs."),
("Under the 'going concern' concept, a business is assumed to:", ["continue operating indefinitely", "close immediately", "be sold", "make losses"], 0, "Financial statements assume ongoing operations."),
("The 'prudence' concept means:", ["not overstating assets or income", "recording all expenses twice", "ignoring losses", "overstating profits"], 0, "Prudence avoids overstating assets/income and understating liabilities."),
("In double entry, every transaction is recorded:", ["twice, once as debit and once as credit", "once only", "three times", "in the cash book only"], 0, "Double entry: equal debits and credits."),
("An increase in an asset is recorded as a:", ["debit", "credit", "journal", "trial balance"], 0, "Assets increase on the debit side."),
("An increase in a liability is recorded as a:", ["credit", "debit", "transfer", "return"], 0, "Liabilities increase on the credit side."),
("An increase in capital is recorded as a:", ["credit", "debit", "receipt", "loss"], 0, "Capital increases on the credit side."),
("A business buys goods on credit. The double entry is:", ["debit Purchases, credit Payables", "debit Payables, credit Purchases", "debit Cash, credit Sales", "debit Sales, credit Cash"], 0, "Purchases increase (debit) and the amount owed increases (credit)."),
("Cash sales of $500 are recorded as:", ["debit Cash, credit Sales", "debit Sales, credit Cash", "debit Cash, credit Purchases", "debit Bank, credit Payables"], 0, "Cash increases (debit) and sales revenue increases (credit)."),
("A payment of $300 to a creditor is recorded as:", ["debit Payables, credit Bank", "debit Bank, credit Payables", "debit Cash, credit Sales", "debit Purchases, credit Bank"], 0, "Paying reduces the amount owed (debit) and reduces cash (credit)."),
("The book of original entry for credit sales is the:", ["sales journal", "cash book", "general journal", "purchases journal"], 0, "Credit sales are first recorded in the sales journal."),
("The purchases journal records:", ["credit purchases", "cash purchases", "credit sales", "returns inwards"], 0, "Credit purchases are recorded in the purchases journal."),
("Which document is issued when goods are returned by a customer?", ["Credit note", "Debit note", "Invoice", "Receipt"], 0, "A credit note reduces what the customer owes."),
("A 'debit note' is issued to:", ["request an adjustment for overcharge or returns", "confirm a sale", "record cash received", "pay wages"], 0, "Debit notes notify suppliers of returns/overcharges."),
("The petty cash book is used to record:", ["small cash payments", "credit sales", "large bank transfers", "depreciation"], 0, "Petty cash covers minor day-to-day expenses."),
("The imprest system of petty cash means:", ["the float is restored to a fixed amount", "no cash is used", "all payments are large", "cash is never counted"], 0, "Under imprest, the float is topped up to the fixed amount."),
("A 'contra entry' occurs when:", ["cash is transferred to the bank", "a sale is made", "goods are returned", "wages are paid"], 0, "Contra entries appear in both cash and bank columns of the cash book."),
("The cash book serves as:", ["both a book of original entry and a ledger account", "only a journal", "only a ledger", "a financial statement"], 0, "The cash book is both journal and ledger for cash/bank."),
("A bank overdraft is a:", ["liability", "current asset", "fixed asset", "capital"], 0, "An overdraft is money owed to the bank."),
("When a cheque received from a customer is dishonoured, it is:", ["debited to the customer's account", "credited to the bank", "recorded as profit", "ignored"], 0, "The receivable is reinstated with a debit."),
("Which of the following is an expense?", ["Rent paid", "Inventory", "Equipment", "Cash"], 0, "Rent is a cost of running the business."),
("Salaries paid in cash are recorded as:", ["debit Salaries, credit Cash", "debit Cash, credit Salaries", "debit Capital, credit Cash", "debit Sales, credit Cash"], 0, "Expenses increase (debit) and cash decreases (credit)."),
("The trial balance is prepared to:", ["check the equality of debits and credits", "calculate profit", "prepare the cash book", "record transactions"], 0, "The trial balance summarises ledger balances."),
("If total debits exceed total credits in the trial balance, the difference is:", ["a debit balance", "a credit balance", "profit", "loss"], 0, "The difference is placed on the smaller side to balance."),
("Which error does NOT affect the trial balance?", ["Error of omission", "Posting to the wrong account", "Recording on the wrong side", "Transposition error"], 0, "Errors that keep debits = credits, like omission, do not affect the TB."),
("An 'error of commission' is when:", ["a transaction is posted to the wrong account of the same class", "a transaction is completely omitted", "the wrong amount is recorded", "both sides are overstated"], 0, "Commission errors use the wrong account of the same category."),
("An 'error of principle' occurs when:", ["an item is posted to the wrong class of account", "a transaction is omitted", "the wrong amount is recorded", "arithmetic is incorrect"], 0, "Principle errors violate accounting rules (e.g. asset as expense)."),
("A suspense account is used to:", ["temporarily hold a trial balance difference", "record profits", "pay dividends", "record cash sales"], 0, "Suspense accounts hold differences pending correction."),
("Gross profit is calculated as:", ["Sales - Cost of Sales", "Sales - Expenses", "Sales + Returns", "Net profit + Drawings"], 0, "Gross profit = sales less cost of goods sold."),
("Cost of sales is calculated as:", ["Opening stock + Purchases - Closing stock", "Purchases - Sales", "Opening stock - Purchases + Closing stock", "Sales - Net profit"], 0, "COS = opening stock + purchases - closing stock."),
("If sales are $50,000 and cost of sales is $35,000, the gross profit is:", ["$15,000", "$85,000", "$50,000", "$35,000"], 0, "50,000 - 35,000 = 15,000."),
("Net profit is:", ["gross profit less expenses", "gross profit plus expenses", "sales less purchases", "assets less liabilities"], 0, "Net profit = gross profit - operating expenses."),
("Which account appears in the Trading Account?", ["Sales", "Rent", "Salaries", "Insurance"], 0, "The trading account shows sales and cost of sales."),
("Closing stock is valued at:", ["cost or net realisable value, whichever is lower", "selling price always", "cost price only", "market price always"], 0, "Prudence requires the lower of cost or NRV."),
("Carriage inwards is:", ["added to purchases", "deducted from sales", "an expense only", "a liability"], 0, "Carriage inwards is part of cost of purchases."),
("Carriage outwards is:", ["an expense in the Profit and Loss account", "added to purchases", "deducted from sales", "a non-current asset"], 0, "Carriage outwards is a selling/distribution expense."),
("Which of the following is a fixed asset?", ["Buildings", "Inventory", "Bank", "Debtors"], 0, "Buildings are long-term productive assets."),
("Depreciation is:", ["the allocation of a fixed asset's cost over its useful life", "the purchase of assets", "a current liability", "cash received"], 0, "Depreciation spreads asset cost over useful life."),
("The straight-line method of depreciation:", ["charges equal depreciation each year", "charges more in early years", "is based on usage", "never charges depreciation"], 0, "Straight-line: (cost - residual)/useful life each year."),
("A machine costs $10,000, residual value $1,000, useful life 5 years. Annual straight-line depreciation is:", ["$1,800", "$2,000", "$1,000", "$9,000"], 0, "(10,000 - 1,000)/5 = 1,800."),
("The reducing balance method:", ["charges more depreciation in early years", "charges equal amounts", "charges nothing", "is used only for land"], 0, "A fixed percentage is charged on the reducing book value."),
("Accumulated depreciation is:", ["a contra asset account", "an expense", "a liability", "revenue"], 0, "Accumulated depreciation reduces the book value of assets."),
("A bad debt is:", ["a debt that will not be paid", "a cash sale", "a prepayment", "an asset"], 0, "Bad debts are uncollectible receivables written off."),
("Writing off a bad debt is recorded as:", ["debit Bad Debts, credit Receivables", "debit Receivables, credit Bad Debts", "debit Cash, credit Sales", "debit Sales, credit Bank"], 0, "The receivable is removed and the expense recorded."),
("A provision for doubtful debts is:", ["an estimate of receivables that may not be collected", "a fixed asset", "cash set aside", "a loan"], 0, "The provision matches possible future losses (prudence)."),
("An accrued expense at year end is:", ["a liability", "an asset", "revenue", "capital"], 0, "Accrued expenses are amounts owed for services used."),
("A prepayment at year end is:", ["a current asset", "a liability", "an expense", "capital"], 0, "Prepayments are payments made in advance — an asset."),
("Rent paid in advance of $1,000 is treated as:", ["a prepayment (asset)", "an accrued expense", "revenue", "drawings"], 0, "Advance payments are prepaid expenses."),
("Wages owing at year end of $800 are:", ["an accrued expense (liability)", "a prepayment", "income", "capital"], 0, "Unpaid wages at year end are accrued expenses."),
("The balance sheet is also known as the:", ["statement of financial position", "income statement", "cash flow statement", "trial balance"], 0, "The balance sheet shows financial position at a date."),
("Working capital is calculated as:", ["Current Assets - Current Liabilities", "Assets + Liabilities", "Capital - Drawings", "Sales - Purchases"], 0, "Working capital measures short-term liquidity."),
("If current assets are $40,000 and current liabilities are $25,000, working capital is:", ["$15,000", "$65,000", "$40,000", "$25,000"], 0, "40,000 - 25,000 = 15,000."),
("Capital employed is:", ["Non-current assets + Working capital", "Total assets only", "Current liabilities", "Drawings"], 0, "Capital employed = total assets - current liabilities."),
("Which of the following is NOT a current liability?", ["Mortgage", "Creditors", "Bank overdraft", "Accrued expenses"], 0, "A mortgage is a long-term (non-current) liability."),
("Owner's drawings reduce:", ["capital", "assets always", "liabilities", "sales"], 0, "Drawings decrease the owner's capital."),
("Drawings are recorded as:", ["debit Drawings, credit Cash/Goods", "credit Drawings, debit Cash", "debit Capital, credit Cash", "debit Sales, credit Cash"], 0, "Drawings increase (debit) and assets decrease (credit)."),
("The current ratio is:", ["Current Assets ÷ Current Liabilities", "Sales ÷ Assets", "Profit ÷ Capital", "Debtors ÷ Creditors"], 0, "Current ratio = current assets / current liabilities."),
("If current assets are $60,000 and current liabilities are $30,000, the current ratio is:", ["2:1", "1:2", "3:1", "1:1"], 0, "60,000/30,000 = 2:1."),
("The acid test (quick) ratio excludes:", ["inventory", "cash", "receivables", "short-term investments"], 0, "Inventory is excluded as the least liquid current asset."),
("Gross profit percentage is:", ["Gross profit ÷ Sales × 100", "Net profit ÷ Sales", "Sales ÷ Gross profit", "Purchases ÷ Sales"], 0, "Gross profit margin = GP/Sales × 100%."),
("Net profit margin measures:", ["the profit left after expenses per dollar of sales", "gross profit", "liquidity", "asset turnover"], 0, "Net margin = Net profit/Sales × 100%."),
("Return on capital employed (ROCE) is:", ["Net profit ÷ Capital employed × 100", "Gross profit ÷ Sales", "Current assets ÷ Sales", "Sales ÷ Assets"], 0, "ROCE shows how efficiently capital generates profit."),
("Which ratio measures a business's ability to pay short-term debts?", ["Current ratio", "Gross profit margin", "Net profit margin", "Gearing ratio"], 0, "Liquidity ratios like the current ratio assess short-term solvency."),
("The bank reconciliation statement is prepared to:", ["explain differences between cash book and bank statement", "calculate profit", "prepare tax returns", "record sales"], 0, "It reconciles the cash book balance with the bank statement."),
("An unpresented cheque is one that:", ["is issued but not yet presented to the bank", "has been returned unpaid", "is lost", "is cancelled"], 0, "Unpresented cheques cause timing differences."),
("A bank 'credit transfer' (direct debit) in the bank statement but not in the cash book is:", ["added to the cash book balance", "subtracted from the cash book", "ignored", "an error"], 0, "Update the cash book for such items first."),
("Which of the following is a cash flow item?", ["Cash received from customers", "Depreciation", "Credit sales", "Bad debts written off"], 0, "Cash flows record actual cash movements."),
("The cash flow statement classifies flows into:", ["operating, investing and financing", "debit and credit", "assets and liabilities", "income and expenses only"], 0, "Cash flows are grouped into these three activities."),
("Depreciation is added back to net profit in the cash flow statement because it is:", ["a non-cash expense", "cash received", "an asset", "a liability"], 0, "Depreciation does not involve cash outflow."),
("Which of the following is a financing activity?", ["Issuing shares", "Buying equipment", "Paying suppliers", "Collecting receivables"], 0, "Share issues raise finance."),
("A control account for receivables is used to:", ["verify the accuracy of the sales ledger", "record cash sales", "calculate depreciation", "prepare the balance sheet"], 0, "The receivables control account checks the sales ledger."),
("The sales ledger contains accounts of:", ["credit customers", "creditors", "the owner", "the bank"], 0, "The sales ledger tracks amounts owed by customers."),
("The purchases ledger contains accounts of:", ["suppliers (creditors)", "customers", "employees", "shareholders"], 0, "The purchases ledger tracks amounts owed to suppliers."),
("In the receivables control account, cash received from customers is:", ["credited", "debited", "ignored", "transferred"], 0, "Cash received reduces receivables (credit)."),
("A partnership is a business owned by:", ["two or more persons", "one person", "shareholders", "the government"], 0, "Partnerships have two or more partners."),
("In a partnership, profit is shared according to:", ["the partnership agreement", "the law always", "who works hardest", "equal shares always"], 0, "The partnership agreement governs profit sharing."),
("Interest on partners' capital is:", ["an appropriation of profit", "an expense always", "a liability", "drawings"], 0, "It is part of profit distribution, not an expense."),
("A limited liability company's owners are called:", ["shareholders", "partners", "debtors", "creditors"], 0, "Shareholders own companies via shares."),
("The capital of a company is divided into:", ["shares", "drawings", "debts", "credits"], 0, "Companies raise capital by issuing shares."),
("Which of the following reduces capital?", ["Drawings", "Profits", "Sale of assets", "New loans"], 0, "Drawings reduce the owner's capital."),
("The statement of cash flows helps users to:", ["assess liquidity and solvency", "measure gross profit only", "value inventory", "record journal entries"], 0, "Cash flow statements reveal cash position and trends."),
("Which document shows money owed by the business to a supplier?", ["Statement of account", "Invoice from customer", "Receipt", "Credit note"], 0, "A supplier's statement lists transactions and the balance due."),
("The period of accounts is called the:", ["accounting period", "budget", "ledger", "journal"], 0, "Financial statements cover an accounting period (e.g. one year)."),
("Which of the following is an example of revenue expenditure?", ["Repair costs", "Buying a building", "Buying equipment", "Legal costs of incorporation"], 0, "Repairs maintain assets — revenue expenditure."),
("Capital expenditure includes:", ["purchase of a delivery van", "petrol for the van", "van repairs", "insurance"], 0, "Buying the van is capital; running costs are revenue."),
("A budget is:", ["a plan of future income and expenses", "a record of past sales", "a trial balance", "a cash book"], 0, "Budgets forecast future financial activity."),
("Which of the following is an internal user of accounts?", ["Managers", "Tax authorities", "Investors", "Banks"], 0, "Managers use accounts internally for decisions."),
]
