# CSEC Spanish practice questions (p13-p100)
# Format: (question, [4 options], answer_index, explanation)
QUESTIONS = [
("How do you say 'good morning' in Spanish?", ["Buenos días", "Buenas noches", "Buenas tardes", "Hola"], 0, "'Buenos días' is used in the morning."),
("What does 'adiós' mean?", ["Goodbye", "Hello", "Please", "Thank you"], 0, "'Adiós' means goodbye."),
("Which is the correct Spanish for 'please'?", ["Por favor", "De nada", "Lo siento", "Perdón"], 0, "'Por favor' means please."),
("How do you say 'thank you' in Spanish?", ["Gracias", "Salud", "Felicidades", "Bienvenido"], 0, "'Gracias' means thank you."),
("What is the Spanish word for 'water'?", ["Agua", "Pan", "Leche", "Jugo"], 0, "'Agua' means water."),
("Which word means 'food' in Spanish?", ["Comida", "Casa", "Escuela", "Trabajo"], 0, "'Comida' means food."),
("How do you say 'I am' in Spanish?", ["Yo soy / Yo estoy", "Yo tengo", "Yo voy", "Yo hago"], 0, "'Soy' (ser) or 'estoy' (estar) mean 'I am'."),
("The correct response to '¿Cómo estás?' is:", ["Estoy bien, gracias", "Me llamo Juan", "Tengo diez años", "Soy de Jamaica"], 0, "'¿Cómo estás?' asks how you are."),
("What is the Spanish for 'my name is'?", ["Me llamo", "Me gusta", "Me duele", "Me voy"], 0, "'Me llamo' introduces your name."),
("How do you say 'I am from Trinidad' in Spanish?", ["Soy de Trinidad", "Voy a Trinidad", "Vivo en Trinidad", "Trabajo en Trinidad"], 0, "'Soy de' means 'I am from'."),
("What does '¿Dónde vives?' mean?", ["Where do you live?", "What is your name?", "How old are you?", "Where are you going?"], 0, "'¿Dónde vives?' asks where you live."),
("How do you say 'I live in Port of Spain' in Spanish?", ["Vivo en Puerto España", "Vengo de Puerto España", "Estoy en Puerto España", "Voy a Puerto España"], 0, "'Vivo en' means 'I live in'."),
("What is the Spanish word for 'house'?", ["La casa", "El carro", "El libro", "La mesa"], 0, "'La casa' means the house."),
("Which word means 'school' in Spanish?", ["La escuela", "La iglesia", "La playa", "La tienda"], 0, "'La escuela' means school."),
("What does 'la familia' mean?", ["The family", "The friends", "The teachers", "The neighbours"], 0, "'La familia' is the family."),
("Which is the Spanish word for 'mother'?", ["La madre", "El padre", "El hermano", "La hermana"], 0, "'La madre' means mother."),
("How do you say 'father' in Spanish?", ["El padre", "La madre", "El abuelo", "El tío"], 0, "'El padre' means father."),
("What is the plural of 'el libro' (the book)?", ["Los libros", "Las libros", "El libros", "Un libros"], 0, "Masculine plural uses 'los'."),
("Choose the correct definite article for 'la mesa' (table):", ["la", "el", "los", "las"], 0, "'Mesa' is feminine singular → 'la'."),
("Which word is feminine?", ["La ventana", "El zapato", "El reloj", "El sombrero"], 0, "'Ventana' is feminine (ends in -a)."),
("How do you say 'one' in Spanish?", ["Uno", "Dos", "Tres", "Cuatro"], 0, "'Uno' means one."),
("What is 'cinco' in English?", ["Five", "Four", "Six", "Ten"], 0, "'Cinco' = five."),
("How do you say 'ten' in Spanish?", ["Diez", "Veinte", "Cien", "Doce"], 0, "'Diez' means ten."),
("What is 'veinte' in English?", ["Twenty", "Twelve", "Two", "Fifty"], 0, "'Veinte' = twenty."),
("Which Spanish word means 'today'?", ["Hoy", "Ayer", "Mañana", "Noche"], 0, "'Hoy' means today; 'mañana' means tomorrow/morning."),
("What does 'mañana' mean?", ["Tomorrow or morning", "Yesterday", "Tonight", "Always"], 0, "'Mañana' can mean tomorrow or morning."),
("How do you say 'yesterday' in Spanish?", ["Ayer", "Hoy", "Mañana", "Ahora"], 0, "'Ayer' means yesterday."),
("What is the Spanish for 'now'?", ["Ahora", "Luego", "Siempre", "Nunca"], 0, "'Ahora' means now."),
("Which word means 'always' in Spanish?", ["Siempre", "Nunca", "A veces", "A menudo"], 0, "'Siempre' means always."),
("What does 'nunca' mean?", ["Never", "Always", "Sometimes", "Often"], 0, "'Nunca' means never."),
("How do you say 'I like' in Spanish?", ["Me gusta", "Me llamo", "Me duele", "Me levanto"], 0, "'Me gusta' expresses liking."),
("What does 'me gusta el fútbol' mean?", ["I like football", "I play football", "I watch football", "I hate football"], 0, "'Me gusta' + noun = I like..."),
("How do you say 'I love you' in Spanish?", ["Te quiero / Te amo", "Te veo", "Te llamo", "Te espero"], 0, "'Te quiero' or 'Te amo' express love."),
("Which is the Spanish for 'friend' (male)?", ["El amigo", "La amiga", "El hermano", "El primo"], 0, "'El amigo' is a male friend."),
("What is 'la playa' in English?", ["The beach", "The park", "The pool", "The mountain"], 0, "'La playa' = the beach."),
("Which word means 'car' in Spanish?", ["El carro / El coche", "El avión", "El barco", "El tren"], 0, "'Carro' (Latin America) or 'coche' (Spain) mean car."),
("How do you say 'train' in Spanish?", ["El tren", "El avión", "El barco", "La bicicleta"], 0, "'El tren' means train."),
("What does 'el aeropuerto' mean?", ["The airport", "The station", "The harbour", "The bus stop"], 0, "'El aeropuerto' is the airport."),
("Which word means 'street' in Spanish?", ["La calle", "La esquina", "La plaza", "El edificio"], 0, "'La calle' means street."),
("How do you say 'the market' in Spanish?", ["El mercado", "El supermercado", "La farmacia", "La tienda"], 0, "'El mercado' is the market."),
("What is 'la farmacia' in English?", ["The pharmacy", "The bakery", "The bank", "The post office"], 0, "'La farmacia' = the pharmacy."),
("Which Spanish word means 'bread'?", ["El pan", "El queso", "La carne", "El arroz"], 0, "'El pan' means bread."),
("What does 'el desayuno' mean?", ["Breakfast", "Lunch", "Dinner", "Snack"], 0, "'El desayuno' is breakfast."),
("How do you say 'lunch' in Spanish?", ["El almuerzo", "El desayuno", "La cena", "La merienda"], 0, "'El almuerzo' means lunch."),
("What is 'la cena' in English?", ["Dinner", "Breakfast", "Lunch", "Dessert"], 0, "'La cena' = dinner."),
("Which word means 'apple' in Spanish?", ["La manzana", "La naranja", "El plátano", "La uva"], 0, "'La manzana' means apple."),
("What does 'el pollo' mean?", ["Chicken", "Beef", "Fish", "Pork"], 0, "'El pollo' means chicken."),
("Which Spanish word means 'cheese'?", ["El queso", "El azúcar", "La sal", "La mantequilla"], 0, "'El queso' means cheese."),
("How do you say 'I am hungry' in Spanish?", ["Tengo hambre", "Tengo sed", "Tengo sueño", "Tengo prisa"], 0, "'Tener hambre' = to be hungry."),
("What does 'tengo sed' mean?", ["I am thirsty", "I am hungry", "I am tired", "I am cold"], 0, "'Tener sed' = to be thirsty."),
("How do you say 'I am tired' in Spanish?", ["Estoy cansado", "Estoy contento", "Estoy enfermo", "Estoy ocupado"], 0, "'Estar cansado' = to be tired."),
("Which phrase means 'I am sick'?", ["Estoy enfermo", "Estoy bien", "Estoy triste", "Estoy feliz"], 0, "'Enfermo' means sick."),
("What does 'estoy feliz' mean?", ["I am happy", "I am sad", "I am angry", "I am nervous"], 0, "'Feliz' = happy."),
("How do you say 'it is hot' (weather) in Spanish?", ["Hace calor", "Hace frío", "Hace viento", "Llueve"], 0, "'Hace calor' means it is hot."),
("What does 'hace frío' mean?", ["It is cold", "It is hot", "It is windy", "It is raining"], 0, "'Hace frío' = it is cold."),
("Which phrase means 'it is raining' in Spanish?", ["Llueve", "Nieva", "Hace sol", "Hay niebla"], 0, "'Llueve' means it is raining."),
("How do you say 'the sun' in Spanish?", ["El sol", "La luna", "La estrella", "El cielo"], 0, "'El sol' means the sun."),
("What is 'la luna' in English?", ["The moon", "The sun", "The star", "The sky"], 0, "'La luna' = the moon."),
("Which Spanish word means 'sky'?", ["El cielo", "El mar", "La tierra", "El fuego"], 0, "'El cielo' means sky."),
("How do you say 'I go' in Spanish?", ["Voy", "Vienes", "Vamos", "Van"], 0, "'Voy' is the yo form of 'ir'."),
("What is the 'yo' form of 'hablar' (to speak) in the present tense?", ["Hablo", "Hablas", "Habla", "Hablamos"], 0, "Yo hablo — I speak."),
("Which is the correct form of 'comer' for 'tú' (you)?", ["Comes", "Como", "Come", "Comemos"], 0, "Tú comes — you eat."),
("What is the 'nosotros' form of 'vivir' (to live)?", ["Vivimos", "Vivo", "Vives", "Viven"], 0, "Nosotros vivimos — we live."),
("Which is the correct form of 'ser' for 'ellos' (they)?", ["Son", "Es", "Soy", "Eres"], 0, "Ellos son — they are."),
("What does 'tener' mean?", ["To have", "To be", "To do", "To go"], 0, "'Tener' means to have."),
("Which form of 'tener' is used with 'yo'?", ["Tengo", "Tienes", "Tiene", "Tenemos"], 0, "Yo tengo — I have."),
("What is 'hacer' in English?", ["To do/make", "To have", "To go", "To come"], 0, "'Hacer' means to do or make."),
("How do you say 'I am going to study' using 'ir + a + infinitive'?", ["Voy a estudiar", "Estudio", "He estudiado", "Estudié"], 0, "Ir a + infinitive expresses near future: voy a estudiar."),
("Which sentence is grammatically correct?", ["Yo voy al mercado", "Yo voy a el mercado", "Yo va al mercado", "Yo vas al mercado"], 0, "'Voy a + el = al' and 'yo voy' are correct."),
("What does '¿Qué hora es?' mean?", ["What time is it?", "What day is it?", "Where is it?", "Who is it?"], 0, "'¿Qué hora es?' asks the time."),
("How do you say 'It is two o'clock' in Spanish?", ["Son las dos", "Es la una", "Son las tres", "Son las cinco"], 0, "Plural hours use 'son las'."),
("What does 'la una' mean in telling time?", ["One o'clock", "Two o'clock", "Half past one", "Quarter to one"], 0, "'Es la una' = it is one o'clock."),
("Which word means 'Monday' in Spanish?", ["Lunes", "Martes", "Miércoles", "Domingo"], 0, "'Lunes' is Monday."),
("What is 'domingo' in English?", ["Sunday", "Saturday", "Monday", "Friday"], 0, "'Domingo' = Sunday."),
("How do you say 'week' in Spanish?", ["La semana", "El mes", "El año", "El día"], 0, "'La semana' means the week."),
("Which Spanish word means 'month'?", ["El mes", "El año", "La semana", "El día"], 0, "'El mes' means month."),
("What is 'enero' in English?", ["January", "June", "July", "December"], 0, "'Enero' = January."),
("How do you say 'today is Monday' in Spanish?", ["Hoy es lunes", "Hoy es martes", "Mañana es lunes", "Ayer fue lunes"], 0, "'Hoy es' + day = today is..."),
("What does '¿Cuánto cuesta?' mean?", ["How much does it cost?", "How old are you?", "Where is it?", "When is it?"], 0, "'¿Cuánto cuesta?' asks the price."),
("Which phrase would you use to order a coffee politely?", ["Quisiera un café, por favor", "¡Dame café ahora!", "Café, rápido", "No quiero café"], 0, "'Quisiera... por favor' is polite."),
("What does 'la cuenta, por favor' mean?", ["The bill, please", "The menu, please", "The table, please", "The water, please"], 0, "'La cuenta' is the bill."),
("In a restaurant, 'la carta' refers to:", ["the menu", "the letter", "the bill", "the napkin"], 0, "'La carta' can mean the menu."),
("What does the sign 'Abierto' mean?", ["Open", "Closed", "Reserved", "For sale"], 0, "'Abierto' means open; 'cerrado' means closed."),
("What does 'peligro' mean?", ["Danger", "Exit", "Entrance", "Caution only"], 0, "'Peligro' means danger."),
("Which sign would you see at an exit?", ["Salida", "Entrada", "Prohibido", "Baños"], 0, "'Salida' means exit."),
("What does 'prohibido fumar' mean?", ["No smoking", "No parking", "No entry", "No running"], 0, "'Prohibido fumar' = smoking forbidden."),
("Which Spanish-speaking country is in the Caribbean?", ["Cuba", "Brazil", "Haiti", "Jamaica"], 0, "Cuba is a Spanish-speaking Caribbean nation."),
("The Day of the Dead ('Día de los Muertos') is mainly celebrated in:", ["Mexico", "Spain", "Argentina", "Puerto Rico"], 0, "Día de los Muertos is a Mexican tradition."),
("What is 'la Navidad' in English?", ["Christmas", "Easter", "New Year", "Carnival"], 0, "'La Navidad' means Christmas."),
("Which festival is famous in Trinidad but also celebrated in Spanish-speaking countries?", ["Carnival", "Thanksgiving", "Hanukkah", "Eid"], 0, "Carnival ('Carnaval') is celebrated across the Caribbean and Latin America."),
("What is the capital of Spain?", ["Madrid", "Barcelona", "Seville", "Valencia"], 0, "Madrid is Spain's capital."),
("Which of these is a Spanish-speaking country in South America?", ["Colombia", "Jamaica", "Brazil", "Belize"], 0, "Colombia is Spanish-speaking; Brazil speaks Portuguese."),
("What does 'bienvenido' mean?", ["Welcome", "Goodbye", "Good luck", "See you later"], 0, "'Bienvenido' means welcome."),
]
