# CSEC English A practice questions (p13-p100)
# Format: (question, [4 options], answer_index, explanation)
QUESTIONS = [
("Which of the following sentences is in the passive voice?", ["The chef cooked the meal.", "The meal was cooked by the chef.", "The chef is cooking the meal.", "The chef will cook the meal."], 1, "In passive voice, the subject receives the action: 'The meal was cooked'."),
("Choose the correct form: 'Neither of the boys ___ present.'", ["was", "were", "are", "have been"], 0, "'Neither' takes a singular verb: 'was'."),
("What is the antonym of 'candid'?", ["frank", "secretive", "open", "honest"], 1, "'Candid' means honest/open; the opposite is 'secretive'."),
("Identify the correctly spelt word:", ["accommodate", "accomodate", "acommodate", "acomodate"], 0, "'Accommodate' has double c and double m."),
("Which sentence uses the colon correctly?", ["She bought: apples, pears and grapes.", "She bought apples, pears: and grapes.", "She bought the following: apples, pears and grapes.", "She bought: apples, pears and grapes."], 2, "A colon introduces a list only after a complete sentence."),
("The prefix 'inter-' in 'international' means:", ["between", "within", "against", "self"], 0, "'Inter-' means between or among."),
("Choose the best synonym for 'hasten'.", ["hurry", "delay", "stop", "ignore"], 0, "'Hasten' means to hurry or move quickly."),
("Which word is a conjunction?", ["because", "quickly", "under", "beautiful"], 0, "'Because' joins clauses; the others are adverb, preposition, adjective."),
("What is the plural of 'analysis'?", ["analyses", "analysises", "analysi", "analyzes"], 0, "Words ending in -sis form plurals by changing to -ses."),
("Identify the figure of speech: 'The wind whispered through the trees.'", ["personification", "simile", "metaphor", "alliteration"], 0, "The wind is given human qualities (whispering)."),
("Which sentence is correctly punctuated?", ["'Hello,' she said.", "'Hello' she said.", "'Hello,' She said.", "'Hello.' she said,"], 0, "Comma after the greeting, inside the quotation marks."),
("The word 'benevolent' most nearly means:", ["kind", "wealthy", "famous", "strict"], 0, "'Benevolent' means well-meaning and kind."),
("Choose the correct pronoun: 'Everyone must bring ___ own lunch.'", ["their", "his or her", "them", "they"], 0, "With 'everyone', singular 'his or her' is formally correct."),
("Which of the following is a compound sentence?", ["She slept and dreamed.", "Tired, she slept.", "She slept peacefully.", "Because she was tired, she slept."], 0, "Two independent clauses joined by 'and'."),
("What does the idiom 'to bite the bullet' mean?", ["to face a difficult situation bravely", "to eat quickly", "to hurt someone", "to speak harshly"], 0, "It means to endure something painful with courage."),
("Select the correctly spelt word:", ["embarrass", "embarass", "embarras", "embaras"], 0, "'Embarrass' has double r and double s."),
("The opposite of 'expand' is:", ["contract", "enlarge", "extend", "increase"], 0, "'Contract' means to shrink or become smaller."),
("Which sentence contains an adverb?", ["The dog barked loudly.", "The loud dog barked.", "The dog is loud.", "The dog barked all night."], 0, "'Loudly' modifies the verb 'barked'."),
("Choose the correct form: 'She has ___ to the market.'", ["gone", "went", "go", "going"], 0, "Present perfect 'has gone' requires the past participle."),
("In the sentence 'The runner, who trains daily, won the race', the clause 'who trains daily' is:", ["relative clause", "adverbial clause", "noun clause", "main clause"], 0, "It starts with 'who' and modifies 'the runner'."),
("What is the main function of a full stop?", ["to end a declarative sentence", "to ask a question", "to show surprise", "to pause briefly"], 0, "A full stop ends a statement."),
("Which word is an abstract noun?", ["bravery", "table", "river", "teacher"], 0, "'Bravery' is a quality, not a physical object."),
("Choose the correct word: 'The committee ___ agreed on the decision.'", ["has", "have", "were", "are"], 0, "A committee acts as one unit here, so singular 'has'."),
("The suffix '-less' in 'fearless' means:", ["without", "full of", "able to", "one who"], 0, "'-less' means without."),
("Identify the metaphor: 'Time is a thief.'", ["metaphor", "simile", "personification", "hyperbole"], 0, "It compares time to a thief directly, without 'like' or 'as'."),
("Which of the following is a simple sentence?", ["The cat sat on the mat.", "The cat sat on the mat and the dog slept.", "Because the cat sat, the dog slept.", "The cat, which is black, sat."], 0, "One independent clause only."),
("The word 'deceive' means to:", ["mislead", "discover", "decide", "deliver"], 0, "'Deceive' means to trick or mislead."),
("Choose the correct sentence:", ["I look forward to meeting you.", "I look forward to meet you.", "I look forward for meeting you.", "I looking forward to meet you."], 0, "'Look forward to' is followed by the -ing form."),
("What is the antonym of 'ancient'?", ["modern", "old", "aged", "historic"], 0, "'Modern' is the opposite of ancient."),
("Which punctuation mark ends a question?", ["question mark", "exclamation mark", "full stop", "comma"], 0, "A question mark ends an interrogative sentence."),
("Identify the misspelt word:", ["recieve", "believe", "achieve", "grieve"], 0, "'Receive' follows 'i before e except after c'."),
("Choose the correct preposition: 'She is interested ___ music.'", ["in", "on", "at", "for"], 0, "'Interested in' is the correct collocation."),
("The phrase 'at the eleventh hour' means:", ["at the last moment", "at noon", "very early", "at 11 o'clock"], 0, "It means just in time, at the last minute."),
("Which word is an adjective in: 'The quick brown fox jumps.'", ["quick", "brown", "fox", "jumps"], 0, "'Quick' and 'brown' are adjectives; choose the clearest: 'quick'."),
("Choose the correct form: 'If I ___ you, I would apologise.'", ["were", "was", "am", "be"], 0, "In the subjunctive, 'were' is used with 'if I'."),
("The root word in 'transportation' is:", ["port", "trans", "tion", "transpor"], 0, "'Port' (to carry) is the root; trans- and -tion are affixes."),
("Which of these is an example of alliteration?", ["Peter picked a peck of pickled peppers", "He is as strong as an ox", "The world is a stage", "I've told you a million times"], 0, "Repeated initial consonant 'p'."),
("What is the plural of 'child'?", ["children", "childs", "childes", "childrens"], 0, "'Child' is irregular; plural is 'children'."),
("Choose the correctly punctuated sentence:", ["He asked, 'Where are you going?'", "He asked 'Where are you going'?", "He asked where are you going?", "'Where are you going?' he asked."], 0, "Quoted question keeps the question mark inside quotes."),
("The word 'diligent' means:", ["hardworking", "lazy", "careless", "angry"], 0, "'Diligent' means showing care and effort."),
("Which sentence has correct subject-verb agreement?", ["The list of items is on the desk.", "The list of items are on the desk.", "The items of the list is on the desk.", "The list with items are on the desk."], 0, "The subject is 'list' (singular), so 'is'."),
("Identify the onomatopoeia:", ["buzz", "run", "think", "sleep"], 0, "'Buzz' imitates the sound it names."),
("What is the purpose of a topic sentence in a paragraph?", ["to state the main idea", "to give an example", "to conclude the paragraph", "to ask a question"], 0, "A topic sentence expresses the paragraph's main idea."),
("The opposite of 'transparent' is:", ["opaque", "clear", "translucent", "visible"], 0, "'Opaque' means not allowing light through."),
("Choose the correct form: 'He does not ___ football.'", ["play", "plays", "playing", "played"], 0, "After 'does not', use the base form."),
("Which word is a verb in: 'She gave a brilliant performance.'", ["gave", "brilliant", "performance", "she"], 0, "'Gave' is the action word."),
("The comma in 'After dinner, we went home' is used to:", ["separate an introductory phrase", "list items", "join sentences", "show possession"], 0, "A comma follows the introductory phrase 'After dinner'."),
("What does the proverb 'Actions speak louder than words' mean?", ["what you do matters more than what you say", "talking is important", "listen before acting", "words are powerful"], 0, "It emphasises deeds over promises."),
("Which of the following is a compound word?", ["rainbow", "happily", "quickly", "teacher"], 0, "'Rainbow' = rain + bow."),
("Choose the best conjunction: 'Study hard ___ you will fail.'", ["or", "and", "but", "so"], 0, "'Or' presents the alternative consequence."),
("Identify the error: 'The team were playing well when the rain came.' (In formal writing, 'team' as a unit is...)", ["singular — should be 'was'", "correct as written", "plural always", "uncountable"], 0, "As a collective unit, 'team' takes a singular verb in formal usage."),
("The word 'ambiguous' means:", ["having more than one possible meaning", "clearly defined", "very short", "extremely loud"], 0, "'Ambiguous' means open to more than one interpretation."),
("Which sentence uses the semicolon correctly?", ["She was tired; nevertheless, she continued.", "She was tired; and continued.", "She was; tired but continued.", "She was tired; therefore."], 0, "Semicolons join related independent clauses."),
("Choose the correct form: 'This is the book ___ I told you about.'", ["which", "who", "whom", "whose"], 0, "'Which' refers to things (the book)."),
("What is the comparative form of 'good'?", ["better", "gooder", "more good", "best"], 0, "Irregular comparative: good → better."),
("The suffix '-ology' means:", ["study of", "fear of", "full of", "without"], 0, "E.g. biology = study of life."),
("Identify the hyperbole: 'I'm so hungry I could eat a horse.'", ["hyperbole", "simile", "metaphor", "irony"], 0, "Deliberate exaggeration for effect."),
("Choose the correct pronoun: 'The prize was given to Maria and ___.'", ["me", "I", "myself", "mine"], 0, "Object of the preposition 'to' → object pronoun 'me'."),
("The word 'courteous' most nearly means:", ["polite", "rude", "quiet", "bold"], 0, "'Courteous' means polite and respectful."),
("Which is the correct spelling?", ["necessary", "neccessary", "necesary", "necessery"], 0, "'Necessary' — one c, double s."),
("What type of sentence is: 'What a beautiful sunset!'", ["exclamatory", "interrogative", "imperative", "declarative"], 0, "It expresses strong emotion with '!'."),
("Choose the correct form: 'Each of the students ___ a book.'", ["has", "have", "were", "are"], 0, "'Each' is singular → 'has'."),
("The idiom 'break the ice' means:", ["to start a conversation to reduce tension", "to break something frozen", "to be cold", "to end a friendship"], 0, "It means to make people feel more comfortable."),
("Which word is the odd one out?", ["blue", "green", "guitar", "red"], 2, "Guitar is an object; the others are colours."),
("Choose the correct sentence:", ["The data are sufficient.", "The data is sufficient.", "The datas are sufficient.", "The data's sufficient."], 1, "'Data' is commonly treated as singular mass noun in modern usage."),
("The word 'fragile' means:", ["easily broken", "very strong", "heavy", "expensive"], 0, "'Fragile' means delicate and easily damaged."),
("Identify the error: 'He don't like coffee.'", ["don't should be doesn't", "like should be likes", "He should be Him", "no error"], 0, "Third-person singular requires 'doesn't'."),
("Which of the following is a complex sentence?", ["When the bell rang, the students left.", "The students left.", "The students left and the bell rang.", "The bell rang loudly."], 0, "Dependent clause + independent clause."),
("What does the prefix 'anti-' mean?", ["against", "before", "after", "with"], 0, "'Anti-' means against (e.g. anti-war)."),
("Choose the correct form: 'She sings ___ than her sister.'", ["better", "good", "well", "best"], 0, "Comparative of 'well' is 'better'."),
("The phrase 'once in a blue moon' means:", ["rarely", "often", "always", "every month"], 0, "It means very rarely."),
("Which sentence uses 'their' correctly?", ["They left their books at home.", "Their going to the park.", "The dog wagged their tail.", "Their is a car outside."], 0, "'Their' shows possession by 'they'."),
("Identify the simile: 'Her smile was like sunshine.'", ["simile", "metaphor", "personification", "alliteration"], 0, "Uses 'like' to compare."),
("The word 'deficient' means:", ["lacking", "abundant", "sufficient", "excessive"], 0, "'Deficient' means not enough of something."),
("Choose the correct punctuation: 'We visited Paris France and London England.'", ["We visited Paris, France, and London, England.", "We visited Paris France and London England.", "We visited Paris, France and London England.", "We visited Paris France, and London, England."], 0, "Commas separate city and country pairs."),
("What is the superlative form of 'bad'?", ["worst", "badder", "more bad", "baddest"], 0, "Irregular: bad → worse → worst."),
("Which word is a determiner?", ["this", "quickly", "run", "beautiful"], 0, "'This' points to a noun; the others are adverb, verb, adjective."),
("The phrase 'the calm before the storm' refers to:", ["a quiet period before trouble", "weather forecasting", "a peaceful storm", "a loud silence"], 0, "It means a peaceful moment before problems begin."),
("Choose the correct form: 'I wish I ___ more time.'", ["had", "have", "will have", "am having"], 0, "After 'I wish' about the present, use past tense 'had'."),
("The word 'persuade' means to:", ["convince", "confuse", "prevent", "permit"], 0, "'Persuade' means to convince someone."),
("Which sentence is in the present continuous tense?", ["She is reading now.", "She reads daily.", "She read yesterday.", "She has read."], 0, "'is reading' = present continuous."),
("Identify the direct object in: 'John threw the ball.'", ["the ball", "John", "threw", "the"], 0, "The ball receives the action of the verb."),
("What does 'sincerely' indicate in a letter?", ["the closing of a formal letter", "the greeting", "the address", "the date"], 0, "'Yours sincerely' closes formal letters."),
("Choose the correct form: 'There ___ many reasons for this.'", ["are", "is", "was", "be"], 0, "'Reasons' is plural → 'are'."),
("The word 'rural' describes:", ["the countryside", "the city", "the coast", "the desert"], 0, "'Rural' relates to country areas."),
("Which of the following is a proper noun?", ["Mount Kilimanjaro", "mountain", "river", "city"], 0, "It names a specific place and is capitalised."),
("Select the sentence with correct capitalization:", ["We visited the Eiffel Tower in Paris.", "We visited the eiffel tower in paris.", "We visited The Eiffel Tower in Paris.", "We visited the Eiffel tower in paris."], 0, "Proper nouns: Eiffel Tower and Paris are capitalised."),
("The word 'reluctant' means:", ["unwilling", "eager", "quick", "happy"], 0, "'Reluctant' means hesitant or unwilling."),
("Choose the correct form: 'He has lived here ___ 2010.'", ["since", "for", "from", "at"], 0, "'Since' is used with a point in time."),
]
