# CSEC Chemistry practice questions (p13-p100)
# Format: (question, [4 options], answer_index, explanation)
QUESTIONS = [
("Which particle determines the identity of an element?", ["Proton", "Neutron", "Electron", "Photon"], 0, "The number of protons (atomic number) defines the element."),
("An atom with 11 protons, 12 neutrons and 11 electrons has a mass number of:", ["23", "11", "12", "22"], 0, "Mass number = protons + neutrons = 11 + 12 = 23."),
("Isotopes are atoms of the same element with different numbers of:", ["neutrons", "protons", "electrons", "orbitals"], 0, "Isotopes differ in neutron number, hence mass number."),
("Which subatomic particle has a negative charge?", ["Electron", "Proton", "Neutron", "Positron"], 0, "Electrons carry a -1 charge."),
("The electron configuration 2,8,1 corresponds to which element?", ["Sodium", "Magnesium", "Aluminium", "Potassium"], 0, "11 electrons total → atomic number 11 = sodium."),
("Which group of the periodic table contains the noble gases?", ["Group 0", "Group 1", "Group 2", "Group 7"], 0, "Group 0 (18) elements are unreactive noble gases."),
("Elements in the same group have the same number of:", ["outer-shell electrons", "shells", "protons", "neutrons"], 0, "Group number equals outer electrons for main groups."),
("Which element is a halogen?", ["Chlorine", "Sodium", "Magnesium", "Calcium"], 0, "Chlorine is in Group 7, the halogens."),
("Which type of bonding involves the transfer of electrons?", ["Ionic", "Covalent", "Metallic", "Hydrogen"], 0, "Ionic bonding transfers electrons from metal to non-metal."),
("In a covalent bond, electrons are:", ["shared", "transferred", "removed", "created"], 0, "Covalent bonds share electron pairs between atoms."),
("The formula of magnesium chloride is:", ["MgCl₂", "MgCl", "Mg₂Cl", "Mg₂Cl₃"], 0, "Mg²⁺ and Cl⁻ combine in a 1:2 ratio."),
("Which of the following conducts electricity in the solid state?", ["Copper", "Sodium chloride", "Sugar", "Sulphur"], 0, "Metals conduct electricity because of delocalised electrons."),
("Ionic compounds conduct electricity when:", ["molten or dissolved", "solid", "gaseous", "never"], 0, "Free-moving ions carry charge in molten/aqueous state."),
("What is the pH of a neutral solution?", ["7", "0", "14", "1"], 0, "pH 7 is neutral at 25°C."),
("Which of the following is a strong acid?", ["Hydrochloric acid", "Ethanoic acid", "Citric acid", "Carbonic acid"], 0, "HCl ionises completely; the others are weak acids."),
("When an acid reacts with a base, the products are:", ["salt and water", "salt and hydrogen", "salt and carbon dioxide", "water and oxygen"], 0, "Neutralisation produces a salt and water."),
("Which gas is produced when an acid reacts with a metal?", ["Hydrogen", "Oxygen", "Carbon dioxide", "Chlorine"], 0, "Acid + metal → salt + hydrogen."),
("The reaction of an acid with a carbonate produces:", ["carbon dioxide", "hydrogen", "oxygen", "ammonia"], 0, "Carbonates release CO₂ with acids."),
("What is the oxidation number of oxygen in most compounds?", ["-2", "+2", "0", "-1"], 0, "Oxygen usually has an oxidation state of -2."),
("In the reaction Zn + CuSO₄ → ZnSO₄ + Cu, zinc is:", ["oxidised", "reduced", "unchanged", "neutralised"], 0, "Zn loses electrons (0 → +2), so it is oxidised."),
("Reduction is defined as:", ["gain of electrons", "loss of electrons", "gain of oxygen", "gain of protons"], 0, "Reduction is gain of electrons (OIL RIG)."),
("Which is an example of a displacement reaction?", ["Zn + CuSO₄ → ZnSO₄ + Cu", "H₂O → H₂ + O₂", "NaCl → Na + Cl₂", "C + O₂ → CO₂"], 0, "Zinc displaces copper from its salt solution."),
("The rate of a reaction can be increased by:", ["raising temperature", "lowering temperature", "diluting reactants", "adding a solid block"], 0, "Higher temperature increases particle kinetic energy and collisions."),
("A catalyst works by:", ["lowering activation energy", "raising activation energy", "being consumed in the reaction", "cooling the reactants"], 0, "Catalysts provide an alternative pathway with lower activation energy."),
("Increasing the surface area of a solid reactant:", ["increases rate of reaction", "decreases rate", "has no effect", "stops the reaction"], 0, "More surface area → more frequent collisions."),
("Which factor does NOT affect the rate of reaction?", ["Colour of the product", "Temperature", "Concentration", "Surface area"], 0, "Product colour does not influence reaction rate."),
("In an endothermic reaction, heat energy is:", ["absorbed", "released", "unchanged", "converted to light"], 0, "Endothermic reactions absorb heat from surroundings."),
("Which reaction is exothermic?", ["Burning of methane", "Melting of ice", "Photosynthesis", "Dissolving ammonium nitrate"], 0, "Combustion releases heat energy."),
("The mole is defined as:", ["6.02 × 10²³ particles", "1000 particles", "1 gram of substance", "22.4 particles"], 0, "One mole contains Avogadro's number of particles."),
("How many moles are in 44 g of CO₂? (Mr = 44)", ["1 mol", "2 mol", "0.5 mol", "4 mol"], 0, "Moles = mass/molar mass = 44/44 = 1 mol."),
("What mass of sodium hydroxide (Mr = 40) is in 2 moles?", ["80 g", "40 g", "20 g", "120 g"], 0, "Mass = moles × Mr = 2 × 40 = 80 g."),
("The concentration of a solution containing 2 moles of solute in 500 cm³ is:", ["4 mol/dm³", "2 mol/dm³", "1 mol/dm³", "0.5 mol/dm³"], 0, "500 cm³ = 0.5 dm³ → 2/0.5 = 4 mol/dm³."),
("At r.t.p., one mole of gas occupies:", ["24 dm³", "22.4 dm³", "6 dm³", "100 dm³"], 0, "Molar volume at room temperature and pressure is 24 dm³."),
("What volume of CO₂ (in dm³) is produced from 0.5 mol at r.t.p.?", ["12 dm³", "24 dm³", "6 dm³", "48 dm³"], 0, "0.5 × 24 = 12 dm³."),
("Which of these is a mixture?", ["Sea water", "Water", "Salt", "Carbon dioxide"], 0, "Sea water contains dissolved salts — a mixture."),
("The technique used to separate an insoluble solid from a liquid is:", ["filtration", "distillation", "chromatography", "crystallisation"], 0, "Filtration separates insoluble solids from liquids."),
("Simple distillation is used to separate:", ["a solvent from a solution", "two insoluble solids", "two dyes", "two miscible liquids"], 0, "Distillation separates a liquid from a solution by boiling."),
("Which technique separates coloured dyes in a mixture?", ["Chromatography", "Filtration", "Evaporation", "Decanting"], 0, "Chromatography separates substances by their movement through a medium."),
("A substance with a fixed composition and definite properties is:", ["a compound", "a mixture", "an alloy", "a solution"], 0, "Compounds have fixed composition and unique properties."),
("Which state of matter has a definite shape and volume?", ["Solid", "Liquid", "Gas", "Plasma"], 0, "Solids have fixed shape and volume."),
("The change of state from solid directly to gas is called:", ["sublimation", "evaporation", "condensation", "freezing"], 0, "Sublimation, e.g. dry ice → CO₂ gas."),
("Which process releases heat energy?", ["Condensation", "Melting", "Evaporation", "Sublimation"], 0, "Condensation is exothermic (gas → liquid)."),
("The melting point of a pure substance is:", ["sharp and definite", "a range", "always 0°C", "below its boiling point always"], 0, "Pure substances melt at a single sharp temperature."),
("Which of the following is an element?", ["Oxygen", "Water", "Salt", "Sugar"], 0, "Oxygen is an element (O₂); the others are compounds."),
("The symbol for iron is:", ["Fe", "Ir", "I", "F"], 0, "Fe comes from the Latin 'ferrum'."),
("Which non-metal is a liquid at room temperature?", ["Bromine", "Iodine", "Chlorine", "Fluorine"], 0, "Bromine is the only liquid non-metal at r.t.p."),
("Which of these metals reacts most vigorously with cold water?", ["Potassium", "Iron", "Copper", "Zinc"], 0, "Group 1 metals react vigorously; K is the most reactive listed."),
("The reactivity series lists metals in order of:", ["reactivity with oxygen/water/acid", "atomic mass", "density", "melting point"], 0, "Reactivity series ranks metals by how readily they react."),
("Which metal would NOT react with dilute hydrochloric acid?", ["Copper", "Magnesium", "Zinc", "Iron"], 0, "Copper is below hydrogen in the reactivity series."),
("Aluminium is protected from corrosion by:", ["a layer of aluminium oxide", "painting only", "electroplating", "alloying with iron"], 0, "Al₂O₃ forms a protective oxide layer."),
("Rusting of iron requires:", ["oxygen and water", "oxygen only", "water only", "carbon dioxide"], 0, "Both oxygen and water are needed for rusting."),
("Which method protects iron by sacrificial protection?", ["Zinc galvanising", "Painting", "Oiling", "Plastic coating"], 0, "Zinc is more reactive and corrodes instead of iron."),
("Which alloy is made of copper and zinc?", ["Brass", "Bronze", "Steel", "Solder"], 0, "Brass = copper + zinc; bronze = copper + tin."),
("An organic compound containing only carbon and hydrogen is a:", ["hydrocarbon", "carbohydrate", "carbonate", "carbide"], 0, "Hydrocarbons contain only C and H."),
("The general formula for alkanes is:", ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙHₙ"], 0, "Alkanes are saturated: CₙH₂ₙ₊₂."),
("Which is the first member of the alkene series?", ["Ethene", "Methane", "Ethane", "Propyne"], 0, "Ethene (C₂H₄) is the simplest alkene."),
("The functional group of alcohols is:", ["-OH", "-COOH", "-CHO", "-NH₂"], 0, "Alcohols contain the hydroxyl (-OH) group."),
("Which substance is used to test for unsaturation?", ["Bromine water", "Limewater", "Litmus paper", "Silver nitrate"], 0, "Bromine water decolourises in the presence of C=C bonds."),
("Ethanol is produced industrially by:", ["fermentation of sugars", "distillation of oil", "fractional crystallisation", "electrolysis of water"], 0, "Fermentation uses yeast to convert sugars to ethanol."),
("Which gas turns limewater milky?", ["Carbon dioxide", "Oxygen", "Hydrogen", "Ammonia"], 0, "CO₂ forms insoluble calcium carbonate with limewater."),
("Hydrogen gas is tested by:", ["a lighted splint producing a 'pop'", "a glowing splint relighting", "turning limewater milky", "bleaching damp litmus"], 0, "Hydrogen burns with a squeaky pop."),
("Oxygen gas relights:", ["a glowing splint", "a damp blue litmus", "a burning splint with a pop", "limewater"], 0, "Oxygen supports combustion, relighting a glowing splint."),
("Ammonia gas turns damp red litmus:", ["blue", "colourless", "red", "purple"], 0, "Ammonia is alkaline and turns red litmus blue."),
("Which of the following is a greenhouse gas?", ["Methane", "Oxygen", "Nitrogen", "Helium"], 0, "Methane traps heat like CO₂."),
("Acid rain is mainly caused by:", ["oxides of sulphur and nitrogen", "carbon monoxide", "ozone", "hydrogen gas"], 0, "SO₂ and NOₓ dissolve in rainwater to form acids."),
("Which of the following reduces air pollution from vehicles?", ["Catalytic converter", "Lead petrol", "Burning coal", "Exhaust without filter"], 0, "Catalytic converters convert harmful gases to less harmful ones."),
("The Haber process produces:", ["ammonia", "sulphuric acid", "nitric acid", "sodium hydroxide"], 0, "N₂ + 3H₂ ⇌ 2NH₃ over iron catalyst."),
("The raw materials for the Haber process are:", ["nitrogen and hydrogen", "oxygen and hydrogen", "nitrogen and oxygen", "ammonia and water"], 0, "Nitrogen from air and hydrogen from natural gas."),
("Which of these is used as a fertiliser?", ["Ammonium nitrate", "Sodium chloride", "Calcium carbonate", "Silicon dioxide"], 0, "Nitrogen compounds like ammonium nitrate enrich soil."),
("The Contact process produces:", ["sulphuric acid", "ammonia", "chlorine", "nitric acid"], 0, "SO₃ is dissolved in H₂SO₄ to make oleum → H₂SO₄."),
("Electrolysis of brine produces:", ["chlorine, hydrogen and sodium hydroxide", "oxygen and hydrogen", "sodium and chlorine", "water only"], 0, "Brine electrolysis yields Cl₂, H₂ and NaOH."),
("Which electrode is the positive electrode in electrolysis?", ["Anode", "Cathode", "Both", "Neither"], 0, "The anode is positive; cations move to the cathode."),
("During electrolysis of molten lead(II) bromide, lead is formed at the:", ["cathode", "anode", "both electrodes", "solution"], 0, "Pb²⁺ cations gain electrons at the cathode (reduction)."),
("Water is a compound because it:", ["contains two elements chemically combined", "can be filtered", "is a liquid", "contains dissolved gases"], 0, "H₂O has H and O chemically bonded in fixed ratio."),
("Which of the following has the highest boiling point?", ["Salt solution", "Pure water", "Alcohol", "Petrol"], 0, "Dissolved solutes raise the boiling point above 100°C."),
("Solubility is usually expressed as:", ["grams of solute per 100 g of water", "litres per gram", "moles per cm³ only", "percentage of water"], 0, "Standard solubility: g solute/100 g solvent."),
("A saturated solution:", ["contains the maximum dissolved solute at that temperature", "has no water", "is always dilute", "cannot be heated"], 0, "No more solute can dissolve at that temperature."),
("Crystallisation is used to obtain:", ["a soluble salt from its solution", "an insoluble solid", "a gas", "two liquids"], 0, "Evaporation and cooling produce crystals of the solute."),
("Which indicator is red in acid?", ["Litmus", "Universal indicator in alkali", "Phenolphthalein in acid", "Methyl orange in alkali"], 0, "Litmus is red in acid, blue in alkali."),
("A solution with pH 2 is:", ["strongly acidic", "weakly acidic", "neutral", "alkaline"], 0, "pH below 7 is acidic; pH 2 is strongly acidic."),
("Which salt is produced when hydrochloric acid reacts with sodium hydroxide?", ["Sodium chloride", "Sodium sulphate", "Sodium nitrate", "Sodium carbonate"], 0, "HCl + NaOH → NaCl + H₂O."),
("Bases are substances that:", ["neutralise acids", "turn litmus red", "have pH below 7", "release hydrogen with metals"], 0, "Bases accept protons and neutralise acids."),
("Zinc oxide is an example of a:", ["amphoteric oxide", "acidic oxide", "neutral oxide", "noble gas"], 0, "Amphoteric oxides react with both acids and bases."),
("Which oxide is acidic?", ["Carbon dioxide", "Magnesium oxide", "Sodium oxide", "Calcium oxide"], 0, "Non-metal oxides like CO₂ are acidic."),
("The process of extracting aluminium from bauxite uses:", ["electrolysis of molten alumina", "heating with carbon", "filtration", "simple distillation"], 0, "Aluminium is extracted by electrolysis of molten Al₂O₃ in cryolite."),
("Why is cryolite added to bauxite in aluminium extraction?", ["To lower the melting point", "To raise the temperature", "To colour the metal", "To remove impurities only"], 0, "Cryolite lowers the melting point, saving energy."),
("Which metal is extracted by reduction with carbon?", ["Iron", "Sodium", "Calcium", "Potassium"], 0, "Iron oxide is reduced by coke (carbon) in the blast furnace."),
("In the blast furnace, the reducing agent is:", ["carbon monoxide", "limestone", "oxygen", "iron ore"], 0, "CO reduces iron(III) oxide to iron."),
("Which of the following is a use of limestone?", ["Making cement and glass", "Extracting aluminium", "Making ammonia", "Producing chlorine"], 0, "Limestone (CaCO₃) is used in cement, glass and steel."),
("The empirical formula of a compound with 40% C, 6.7% H and 53.3% O (Ar: C=12, H=1, O=16) is:", ["CH₂O", "C₂H₄O₂", "CHO", "C₆H₁₂O₆"], 0, "Moles: C=3.33, H=6.7, O=3.33 → ratio 1:2:1 → CH₂O."),
("Which statement about catalysts is TRUE?", ["They are not used up in the reaction", "They increase activation energy", "They change the products", "They always speed up reactions equally"], 0, "Catalysts remain chemically unchanged after the reaction."),
]
