# CSEC Physics practice questions (p13-p100)
# Format: (question, [4 options], answer_index, explanation)
QUESTIONS = [
("Which of the following is a vector quantity?", ["Velocity", "Speed", "Distance", "Mass"], 0, "Velocity has both magnitude and direction."),
("A car accelerates from rest to 20 m/s in 5 s. What is its acceleration?", ["4 m/s²", "5 m/s²", "100 m/s²", "0.25 m/s²"], 0, "a = (v-u)/t = (20-0)/5 = 4 m/s²."),
("The SI unit of force is the:", ["newton", "joule", "watt", "pascal"], 0, "Force is measured in newtons (N)."),
("A force of 10 N acts on a mass of 2 kg. What is the acceleration?", ["5 m/s²", "20 m/s²", "0.2 m/s²", "8 m/s²"], 0, "F = ma → a = 10/2 = 5 m/s²."),
("Momentum is calculated as:", ["mass × velocity", "mass × acceleration", "force × distance", "mass × speed ÷ time"], 0, "Momentum p = mv."),
("The kinetic energy of a 2 kg object moving at 3 m/s is:", ["9 J", "6 J", "18 J", "12 J"], 0, "KE = ½mv² = ½ × 2 × 9 = 9 J."),
("The gravitational potential energy gained by a 5 kg mass raised 4 m (g = 10 m/s²) is:", ["200 J", "20 J", "50 J", "100 J"], 0, "GPE = mgh = 5 × 10 × 4 = 200 J."),
("The law of conservation of energy states that energy:", ["cannot be created or destroyed", "is always created", "can be destroyed", "exists only as heat"], 0, "Energy is conserved — only converted between forms."),
("Which of the following is NOT a renewable energy source?", ["Coal", "Solar", "Wind", "Hydroelectric"], 0, "Coal is a fossil fuel, which is non-renewable."),
("Power is defined as:", ["work done per unit time", "force per unit area", "energy stored", "mass per unit volume"], 0, "Power = work/time, measured in watts."),
("A machine does 600 J of work in 10 s. Its power output is:", ["60 W", "600 W", "6 W", "6000 W"], 0, "P = 600/10 = 60 W."),
("The efficiency of a machine is:", ["useful output ÷ input × 100%", "input ÷ output", "output × input", "input - output"], 0, "Efficiency = (useful energy out / energy in) × 100%."),
("Which simple machine is a ramp?", ["Inclined plane", "Lever", "Pulley", "Wheel and axle"], 0, "A ramp is an inclined plane that reduces the force needed."),
("Pressure is defined as:", ["force per unit area", "force × area", "area per unit force", "mass per unit area"], 0, "Pressure = F/A, unit pascal."),
("A force of 50 N acts on an area of 2 m². The pressure is:", ["25 Pa", "100 Pa", "52 Pa", "48 Pa"], 0, "P = 50/2 = 25 Pa."),
("In liquids, pressure:", ["increases with depth", "decreases with depth", "is constant", "is zero at all depths"], 0, "Liquid pressure = hρg, increasing with depth."),
("The upthrust on an object in a fluid is described by:", ["Archimedes' principle", "Newton's first law", "Boyle's law", "Pascal's law"], 0, "Archimedes' principle: upthrust equals weight of displaced fluid."),
("An object floats when:", ["its density is less than the fluid's", "its density is greater", "it is fully submerged always", "its weight is zero"], 0, "Floating requires the object's density < fluid density."),
("A hydraulic press works on:", ["Pascal's principle", "Archimedes' principle", "Bernoulli's principle", "Newton's second law"], 0, "Pascal's principle: pressure transmitted equally in a fluid."),
("The temperature of boiling water at standard pressure is:", ["100°C", "0°C", "212°C", "50°C"], 0, "Water boils at 100°C at standard atmospheric pressure."),
("Heat transfer by the movement of fluids is called:", ["convection", "conduction", "radiation", "insulation"], 0, "Convection involves bulk movement of heated fluid."),
("Which method of heat transfer does NOT require a medium?", ["Radiation", "Conduction", "Convection", "All require a medium"], 0, "Radiation transfers heat by electromagnetic waves."),
("Which colour surface is the best absorber of radiation?", ["Black", "White", "Silver", "Red"], 0, "Black surfaces absorb and emit radiation best."),
("Specific heat capacity is the energy needed to:", ["raise 1 kg of a substance by 1°C", "melt 1 kg", "boil 1 kg", "freeze 1 kg"], 0, "c = Q/(mΔT), unit J/kg°C."),
("How much heat is needed to raise 2 kg of water by 5°C? (c = 4200 J/kg°C)", ["42000 J", "4200 J", "8400 J", "21000 J"], 0, "Q = mcΔT = 2 × 4200 × 5 = 42000 J."),
("Latent heat is the energy absorbed during:", ["a change of state at constant temperature", "a temperature rise", "chemical reaction only", "melting always"], 0, "Latent heat changes state without changing temperature."),
("The specific latent heat of fusion relates to:", ["melting/freezing", "boiling/condensing", "sublimation", "expansion"], 0, "Fusion = solid ↔ liquid change."),
("The linear expansivity of a material measures:", ["how much it expands when heated", "how dense it is", "how it conducts heat", "its melting point"], 0, "Linear expansivity = fractional length change per degree."),
("Why do railway tracks have expansion gaps?", ["To allow for expansion in heat", "To save metal", "For decoration", "To prevent theft"], 0, "Gaps prevent buckling when rails expand on hot days."),
("A bimetallic strip bends when heated because:", ["the two metals expand at different rates", "it is magnetic", "it is painted black", "metals contract when heated"], 0, "Different expansivities cause differential bending."),
("A wave transfers:", ["energy", "matter", "mass", "charge always"], 0, "Waves transfer energy without transferring matter."),
("The distance between two successive crests is the:", ["wavelength", "frequency", "amplitude", "period"], 0, "Wavelength λ is the distance between successive crests."),
("The number of waves passing a point per second is the:", ["frequency", "amplitude", "wavelength", "speed"], 0, "Frequency f is measured in hertz."),
("A wave has frequency 20 Hz and wavelength 5 m. Its speed is:", ["100 m/s", "4 m/s", "25 m/s", "15 m/s"], 0, "v = fλ = 20 × 5 = 100 m/s."),
("Which is a longitudinal wave?", ["Sound", "Light", "Water", "Radio"], 0, "Sound waves compress and rarefy along the direction of travel."),
("The amplitude of a wave is:", ["maximum displacement from rest", "distance between crests", "number of waves per second", "time for one wave"], 0, "Amplitude is the maximum displacement."),
("The frequency of a wave with period 0.5 s is:", ["2 Hz", "0.5 Hz", "5 Hz", "50 Hz"], 0, "f = 1/T = 1/0.5 = 2 Hz."),
("Sound cannot travel through:", ["a vacuum", "air", "water", "steel"], 0, "Sound needs a medium; a vacuum has no particles."),
("The speed of sound in air is approximately:", ["340 m/s", "1500 m/s", "3 × 10⁸ m/s", "34 m/s"], 0, "Sound travels at about 340 m/s in air."),
("The phenomenon where sound bounces off a surface is:", ["echo", "refraction", "diffraction", "resonance"], 0, "An echo is reflected sound."),
("Pitch is related to the ___ of a sound wave.", ["frequency", "amplitude", "speed", "wavelength only"], 0, "Higher frequency → higher pitch."),
("Loudness depends on the ___ of a sound wave.", ["amplitude", "frequency", "speed", "phase"], 0, "Greater amplitude → louder sound."),
("Which region of the electromagnetic spectrum has the highest frequency?", ["Gamma rays", "Radio waves", "Visible light", "Microwaves"], 0, "Gamma rays have the shortest wavelength and highest frequency."),
("Visible light is a form of:", ["electromagnetic radiation", "sound", "mechanical wave", "particle only"], 0, "Light is an electromagnetic wave."),
("The speed of light in a vacuum is:", ["3 × 10⁸ m/s", "340 m/s", "3 × 10⁶ m/s", "1.5 × 10⁸ m/s"], 0, "c ≈ 3 × 10⁸ m/s."),
("The law of reflection states that the angle of incidence:", ["equals the angle of reflection", "is double the angle of reflection", "is half the reflection angle", "is unrelated to reflection"], 0, "Angle of incidence = angle of reflection."),
("An image formed by a plane mirror is:", ["virtual, upright, same size", "real, inverted, magnified", "virtual, inverted", "real, upright"], 0, "Plane mirror images are virtual and laterally inverted."),
("The bending of light when it passes into a different medium is:", ["refraction", "reflection", "diffraction", "absorption"], 0, "Refraction occurs due to speed change at the boundary."),
("Which of these can form a real image?", ["Converging lens", "Plane mirror", "Convex mirror", "Concave mirror only when object is close"], 0, "Convex (converging) lenses can form real, inverted images."),
("The focal length of a converging lens is the distance from the lens to:", ["the principal focus", "the object", "the screen", "the centre of curvature"], 0, "Focal length f is from lens to focus."),
("A diverging lens is also called a:", ["concave lens", "convex lens", "converging lens", "magnifying lens"], 0, "Diverging lenses are concave."),
("Refractive index is the ratio of:", ["speed of light in vacuum to speed in medium", "frequency to wavelength", "angle to distance", "mass to volume"], 0, "n = c/v."),
("The critical angle is the angle of incidence that produces:", ["an angle of refraction of 90°", "zero refraction", "total internal reflection always", "a virtual image"], 0, "Beyond the critical angle, total internal reflection occurs."),
("Optical fibres use ___ to transmit light.", ["total internal reflection", "refraction only", "diffraction", "dispersion"], 0, "Total internal reflection keeps light inside the fibre."),
("Which colour of light has the longest wavelength in the visible spectrum?", ["Red", "Violet", "Blue", "Green"], 0, "Red has the longest wavelength; violet the shortest."),
("A prism splits white light into colours because:", ["different colours refract by different amounts", "it reflects colours", "it absorbs white light", "colours move at different speeds in air"], 0, "Dispersion occurs due to different refractive indices per colour."),
("The unit of electric current is the:", ["ampere", "volt", "ohm", "watt"], 0, "Current is measured in amperes (A)."),
("Current is the rate of flow of:", ["charge", "energy", "voltage", "resistance"], 0, "I = Q/t; charge flows in coulombs per second."),
("A current of 2 A flows for 10 s. The charge passed is:", ["20 C", "5 C", "0.2 C", "12 C"], 0, "Q = It = 2 × 10 = 20 C."),
("Potential difference is measured in:", ["volts", "amperes", "ohms", "coulombs"], 0, "Voltage (p.d.) is measured in volts."),
("Ohm's Law states that:", ["V = IR", "V = I/R", "V = R/I", "V = I²R"], 0, "Voltage = current × resistance."),
("A resistor of 4 Ω carries a current of 3 A. The p.d. across it is:", ["12 V", "7 V", "1.33 V", "81 V"], 0, "V = IR = 3 × 4 = 12 V."),
("Resistance is measured in:", ["ohms", "volts", "watts", "amperes"], 0, "Resistance unit is the ohm (Ω)."),
("In a series circuit, the total resistance is:", ["the sum of individual resistances", "the smallest resistance", "the largest resistance", "zero"], 0, "R_total = R₁ + R₂ + ... in series."),
("In a parallel circuit, the potential difference across each branch is:", ["the same", "different", "zero", "half the total"], 0, "Parallel branches share the same p.d."),
("The heating effect of current is used in:", ["electric kettle", "electric fan", "battery charger", "transformer"], 0, "Kettles use resistive heating elements."),
("Power dissipated in a resistor is:", ["P = IV", "P = IR", "P = V/I", "P = I/R"], 0, "P = IV (also I²R or V²/R)."),
("An appliance draws 5 A at 240 V. Its power is:", ["1200 W", "48 W", "235 W", "120 W"], 0, "P = 240 × 5 = 1200 W."),
("Electrical energy is measured in:", ["kilowatt-hours", "watts", "volts", "amperes"], 0, "Bills are based on kWh of energy."),
("A 1 kW appliance runs for 3 hours. The energy used is:", ["3 kWh", "1 kWh", "4 kWh", "0.33 kWh"], 0, "Energy = power × time = 1 × 3 = 3 kWh."),
("Fuses protect circuits by:", ["melting when current is too high", "storing charge", "reducing voltage", "increasing resistance"], 0, "The fuse wire melts, breaking the circuit at excess current."),
("Earthing a metal appliance:", ["prevents electric shock by directing current to ground", "increases current", "reduces voltage", "is for decoration"], 0, "Earth wire provides a low-resistance path for fault current."),
("The SI unit of magnetic flux density is the:", ["tesla", "weber", "henry", "gauss only"], 0, "Magnetic flux density B is measured in tesla (T)."),
("Which material is easily magnetised?", ["Iron", "Copper", "Aluminium", "Plastic"], 0, "Iron is ferromagnetic and easily magnetised."),
("The magnetic field around a current-carrying conductor is:", ["circular", "linear", "spiral", "zero"], 0, "Right-hand grip rule gives circular field lines."),
("An electromagnet is made by:", ["coiling wire around an iron core", "wrapping copper wire only", "using a permanent magnet", "connecting two batteries"], 0, "Current in a coil around soft iron creates a strong magnet."),
("Electromagnetic induction produces:", ["an e.m.f. in a conductor", "permanent magnets", "chemical energy", "sound"], 0, "A changing magnetic field induces an e.m.f."),
("Which of the following increases induced e.m.f.?", ["Faster movement of magnet", "Slower movement", "Weaker magnet", "Removing the coil"], 0, "Faster flux change induces greater e.m.f."),
("Transformers work on:", ["alternating current", "direct current", "static charge", "magnetic monopoles"], 0, "Transformers require changing (AC) current."),
("A step-up transformer:", ["increases voltage, decreases current", "increases current", "decreases voltage only", "stores energy"], 0, "More secondary turns → higher voltage, lower current."),
("The turns ratio of a transformer is 10:1 (primary:secondary). If primary is 240 V, secondary is:", ["24 V", "2400 V", "2.4 V", "240 V"], 0, "Vs = Vp × Ns/Np = 240 × 1/10 = 24 V."),
("The structure of an atom includes protons, neutrons and:", ["electrons", "photons", "positrons", "mesons"], 0, "Atoms contain electrons orbiting the nucleus."),
("Radioactivity is the:", ["spontaneous emission of radiation from unstable nuclei", "emission of light by hot objects", "bending of light", "transfer of heat"], 0, "Unstable nuclei decay spontaneously emitting radiation."),
("Which radiation is a helium nucleus?", ["Alpha", "Beta", "Gamma", "X-ray"], 0, "Alpha particles are 2p + 2n (He nucleus)."),
("Beta particles are:", ["fast-moving electrons", "helium nuclei", "photons", "protons"], 0, "Beta radiation consists of high-speed electrons."),
("Which radiation has the greatest penetrating power?", ["Gamma", "Alpha", "Beta", "All equal"], 0, "Gamma rays penetrate most materials deeply."),
("The half-life of a substance is the time for:", ["half the nuclei to decay", "all nuclei to decay", "radiation to stop", "the mass to double"], 0, "Half-life is the time for activity to halve."),
("If a sample has an activity of 800 Bq and half-life of 10 min, after 30 min the activity is:", ["100 Bq", "400 Bq", "200 Bq", "50 Bq"], 0, "30 min = 3 half-lives: 800 → 400 → 200 → 100 Bq."),
("Background radiation comes from:", ["natural sources like rocks and cosmic rays", "only nuclear reactors", "only mobile phones", "no source"], 0, "Background radiation is natural and always present."),
("Which of the following is a nuclear fission reaction?", ["Uranium nucleus splitting into smaller nuclei", "Two nuclei fusing", "An atom emitting light", "A metal corroding"], 0, "Fission splits a heavy nucleus, releasing energy."),
("Nuclear fusion powers:", ["the sun", "nuclear power stations", "batteries", "solar panels only"], 0, "Fusion of hydrogen nuclei releases the Sun's energy."),
("A thermometer measures temperature using:", ["expansion of a liquid", "electric current", "magnetism", "radioactivity"], 0, "Mercury/alcohol expands with temperature in a thermometer."),
("The unit of frequency is the:", ["hertz", "newton", "joule", "watt"], 0, "Frequency is measured in hertz (Hz)."),
]
