# CSEC Information Technology practice questions (p13-p100)
# Format: (question, [4 options], answer_index, explanation)
QUESTIONS = [
("Which of the following is an input device?", ["Scanner", "Monitor", "Printer", "Speaker"], 0, "A scanner captures data into the computer."),
("Which device is both an input and output device?", ["Touch screen", "Keyboard", "Mouse", "Printer"], 0, "A touch screen displays output and accepts touch input."),
("RAM is best described as:", ["temporary memory for running programs", "permanent storage", "a type of processor", "an input device"], 0, "RAM (random access memory) is volatile, holding data temporarily."),
("Which storage device uses laser light to read data?", ["DVD", "USB flash drive", "Hard disk", "SSD"], 0, "Optical discs like DVDs use lasers."),
("Which is the correct order of data sizes from smallest to largest?", ["bit, byte, kilobyte, megabyte", "byte, bit, kilobyte, megabyte", "kilobyte, byte, bit, megabyte", "megabyte, kilobyte, byte, bit"], 0, "8 bits = 1 byte; 1024 bytes = 1 KB."),
("The CPU is also known as the:", ["processor", "monitor", "hard drive", "motherboard"], 0, "The central processing unit processes instructions."),
("Which component stores data permanently even when the computer is off?", ["Hard disk drive", "RAM", "Cache", "Registers"], 0, "HDDs/SSDs are non-volatile storage."),
("The binary number 1011 in decimal is:", ["11", "9", "13", "10"], 0, "8 + 0 + 2 + 1 = 11."),
("The decimal number 14 in binary is:", ["1110", "1101", "1011", "1001"], 0, "8+4+2 = 14 → 1110."),
("The hexadecimal number 1F in decimal is:", ["31", "15", "19", "16"], 0, "1×16 + 15 = 31."),
("Which of the following is system software?", ["Operating system", "Word processor", "Spreadsheet", "Web browser"], 0, "The OS manages hardware and software resources."),
("Which is an example of application software?", ["Microsoft Excel", "Linux", "Windows 11", "Device drivers"], 0, "Excel is an application; the others are system software."),
("The operating system's main function is to:", ["manage hardware and software resources", "create documents", "connect to the internet only", "print files"], 0, "The OS controls and coordinates all computer resources."),
("Which of these is a function of the operating system?", ["Memory management", "Typing documents", "Designing graphics", "Sending emails"], 0, "The OS manages memory, processes, files and devices."),
("'WYSIWYG' means:", ["What You See Is What You Get", "Write Your Simple Inputs With Your Graphics", "Web Yield System Internet Web Group", "What You Send Is What You Get"], 0, "It describes editors that show the final output as you type."),
("Which file extension indicates a word processing document in Microsoft Word?", [".docx", ".xlsx", ".pptx", ".jpeg"], 0, ".docx is the Word document format."),
("Which spreadsheet function finds the average of a range?", ["=AVERAGE(A1:A10)", "=SUM(A1:A10)", "=COUNT(A1:A10)", "=MAX(A1:A10)"], 0, "AVERAGE calculates the arithmetic mean."),
("In a spreadsheet, the cell reference $A$1 is:", ["absolute", "relative", "mixed only", "circular"], 0, "$A$1 locks both the column and row."),
("Which spreadsheet feature sorts data automatically?", ["Sort", "Filter only", "Format", "Merge"], 0, "Sort arranges data in ascending or descending order."),
("In a database, a row of data is called a:", ["record", "field", "table", "query"], 0, "Records are rows; fields are columns."),
("A primary key in a database:", ["uniquely identifies each record", "is always a number", "can be empty", "duplicates values"], 0, "Primary keys are unique identifiers for records."),
("Which SQL statement retrieves data?", ["SELECT", "INSERT", "UPDATE", "DELETE"], 0, "SELECT queries data from a table."),
("Which SQL clause is used to sort results?", ["ORDER BY", "WHERE", "GROUP BY", "JOIN"], 0, "ORDER BY sorts query results."),
("A database 'query' is used to:", ["extract specific data", "print data", "store paper files", "design reports only"], 0, "Queries retrieve and manipulate selected data."),
("Which of the following is a valid primary key value?", ["Student ID", "First name", "Date of birth", "Gender"], 0, "Student IDs are unique; names/dates can repeat."),
("A LAN is a network that:", ["covers a small area like an office", "covers countries", "spans the globe", "uses satellites only"], 0, "Local Area Networks cover limited geographic areas."),
("The internet is an example of a:", ["WAN", "LAN", "PAN", "MAN"], 0, "A Wide Area Network spans large distances."),
("Which device connects a LAN to the internet?", ["Router", "Hub", "Switch", "Repeater"], 0, "A router routes traffic between networks."),
("The unique address of a device on a network is its:", ["IP address", "password", "username", "file name"], 0, "IP addresses identify devices on networks."),
("In a star topology, if the central hub fails:", ["the whole network stops", "only one computer fails", "nothing changes", "the internet fails"], 0, "All nodes depend on the central hub."),
("Which topology connects all devices to one main cable?", ["Bus topology", "Star topology", "Ring topology", "Mesh topology"], 0, "In a bus, devices share a single backbone cable."),
("The protocol used for web pages is:", ["HTTP", "FTP", "SMTP", "POP3"], 0, "HyperText Transfer Protocol serves web pages."),
("Which protocol is used to send email?", ["SMTP", "HTTP", "FTP", "DNS"], 0, "Simple Mail Transfer Protocol sends email."),
("Which HTML tag creates a hyperlink?", ["<a>", "<link>", "<href>", "<url>"], 0, "The anchor tag <a href=\"...\"> creates links."),
("Which HTML tag is used for the largest heading?", ["<h1>", "<h6>", "<head>", "<heading>"], 0, "<h1> is the largest heading level."),
("Which CSS property changes text colour?", ["color", "font-size", "background", "text-align"], 0, "The color property sets text colour."),
("Which of the following is a programming language?", ["Python", "HTML", "CSS", "HTTP"], 0, "Python is a programming language; HTML/CSS are markup/styling."),
("A variable in programming is:", ["a named storage location for data", "a constant number", "a type of loop", "an input device"], 0, "Variables store values that can change."),
("Which data type stores whole numbers?", ["Integer", "String", "Boolean", "Float"], 0, "Integers are whole numbers without decimals."),
("Which of the following is a boolean value?", ["True", "5", "\"hello\"", "3.14"], 0, "Booleans are True/False."),
("An 'if' statement is used for:", ["decision making", "looping", "storing data", "printing"], 0, "Conditionals execute code based on conditions."),
("Which loop repeats a block a fixed number of times?", ["FOR loop", "WHILE loop", "IF statement", "GOTO"], 0, "FOR loops iterate a known number of times."),
("A 'WHILE' loop continues while:", ["the condition is true", "the condition is false", "the user presses a key", "the program ends"], 0, "WHILE repeats as long as its condition holds."),
("The process of finding and fixing errors in code is called:", ["debugging", "compiling", "running", "linking"], 0, "Debugging removes bugs from programs."),
("Which of the following is an arithmetic operator?", ["+", "=", "==", "<"], 0, "+ performs addition; the others compare or assign."),
("Which symbol is used for assignment in most languages?", ["=", "==", "===", "!="], 0, "Single '=' assigns a value."),
("A function is best described as:", ["a reusable block of code", "a type of variable", "an error", "a hardware part"], 0, "Functions group code for reuse."),
("Pseudocode is:", ["a plain-language description of an algorithm", "executable code", "a programming language", "a flowchart"], 0, "Pseudocode describes logic without strict syntax."),
("Which symbol in a flowchart represents a decision?", ["Diamond", "Rectangle", "Oval", "Arrow"], 0, "Diamonds represent decisions/branches."),
("The oval symbol in a flowchart represents:", ["start or end", "process", "input/output", "decision"], 0, "Ovals mark the beginning or end of a flowchart."),
("Which of these is a search engine?", ["Google", "Chrome", "Windows", "Excel"], 0, "Google is a search engine; Chrome is a browser."),
("'Phishing' is a technique used to:", ["steal personal information via fake messages", "increase internet speed", "repair computers", "backup files"], 0, "Phishing tricks users into revealing credentials."),
("A computer virus is:", ["a malicious program", "a hardware fault", "a type of browser", "an antivirus tool"], 0, "Viruses are malicious software that spread and damage."),
("Which of the following helps protect against viruses?", ["Antivirus software", "Deleting system files", "Opening unknown attachments", "Turning off the firewall"], 0, "Antivirus detects and removes malware."),
("A firewall is used to:", ["block unauthorised network access", "speed up the CPU", "store passwords", "create documents"], 0, "Firewalls filter network traffic for security."),
("Strong passwords should:", ["contain letters, numbers and symbols", "be short", "be easy to guess", "be reused everywhere"], 0, "Complex passwords resist guessing attacks."),
("Copyright law protects:", ["original creative works", "hardware only", "internet speed", "computer brands"], 0, "Copyright covers creative and intellectual works."),
("Plagiarism is:", ["using others' work without credit", "creating original work", "citing sources", "proofreading"], 0, "Plagiarism presents others' work as your own."),
("Which of the following is an example of a peripheral device?", ["Printer", "CPU", "RAM", "Motherboard"], 0, "Peripherals connect to the computer externally."),
("The motherboard is:", ["the main circuit board", "a storage device", "an input device", "an output device"], 0, "The motherboard connects all major components."),
("Which unit measures processor speed?", ["GHz", "GB", "DPI", "PPM"], 0, "Gigahertz measures clock speed."),
("Which of the following is a type of non-volatile storage?", ["SSD", "RAM", "Cache", "Register"], 0, "SSDs retain data without power."),
("A solid-state drive (SSD) uses:", ["flash memory", "magnetic disks", "lasers", "magnetic tape"], 0, "SSDs use NAND flash memory with no moving parts."),
("Which printer uses toner powder?", ["Laser printer", "Inkjet printer", "Dot matrix", "Thermal printer"], 0, "Laser printers fuse toner onto paper."),
("Inkjet printers work by:", ["spraying liquid ink", "melting toner", "striking ribbons", "burning dots"], 0, "Inkjets spray tiny ink droplets."),
("Which of the following is an example of e-commerce?", ["Buying goods online", "Emailing a friend", "Downloading software legally", "Streaming music"], 0, "E-commerce is buying/selling over the internet."),
("Cloud computing means:", ["storing and accessing data over the internet", "using a local hard drive", "printing documents", "installing software manually"], 0, "Cloud services host data and apps remotely."),
("Which of the following is a cloud storage service?", ["Google Drive", "Microsoft Word", "VLC Player", "Chrome"], 0, "Google Drive stores files online."),
("Multimedia combines:", ["text, graphics, audio and video", "only text", "only images", "only sound"], 0, "Multimedia integrates multiple media types."),
("Which file format is used for images?", [".png", ".mp3", ".docx", ".exe"], 0, "PNG is an image format; mp3 is audio."),
("Which file format is used for video?", [".mp4", ".jpg", ".txt", ".pdf"], 0, "MP4 is a video container format."),
("The resolution of a monitor is measured in:", ["pixels", "inches", "hertz", "watts"], 0, "Resolution = number of pixels (e.g. 1920×1080)."),
("Which of these is a presentation software?", ["PowerPoint", "Excel", "Access", "Notepad"], 0, "PowerPoint creates presentations."),
("A 'mail merge' is used to:", ["send personalised letters to many people", "merge two documents", "combine audio files", "merge cells"], 0, "Mail merge combines a template with a data source."),
("Which of the following best describes 'big data'?", ["Very large datasets analysed computationally", "Small data files", "Data on paper", "Backup files"], 0, "Big data requires special tools to process at scale."),
("Artificial intelligence refers to:", ["machines performing tasks that require human intelligence", "larger hard drives", "faster internet", "better printers"], 0, "AI simulates human-like reasoning and learning."),
("Robotics is the field of:", ["building and programming robots", "designing websites", "database administration", "network cabling"], 0, "Robotics combines engineering and programming."),
("Which of the following is a wearable technology?", ["Smartwatch", "Desktop computer", "Printer", "Router"], 0, "Smartwatches are worn on the body."),
("A 'cookie' on a website is used to:", ["store user preferences", "increase speed", "delete files", "print pages"], 0, "Cookies remember user settings and sessions."),
("Two-factor authentication adds:", ["a second verification step", "faster login", "more storage", "better graphics"], 0, "2FA requires an extra check like a code."),
("Which of the following is ethical use of technology?", ["Respecting others' privacy", "Hacking accounts", "Spreading false news", "Pirating software"], 0, "Ethics means responsible, honest use."),
("A backup is important because it:", ["protects against data loss", "speeds up the computer", "increases memory", "reduces cost"], 0, "Backups restore data after failures."),
("The most effective backup strategy is:", ["regular automated backups", "one manual copy", "no backups", "backup only after a crash"], 0, "Regular backups minimise data loss."),
("Which of these can prevent data loss during a power outage?", ["UPS (Uninterruptible Power Supply)", "Larger monitor", "Faster processor", "Better keyboard"], 0, "A UPS provides temporary power to save work."),
("Which of the following describes 'telecommuting'?", ["Working from home using technology", "Travelling to work", "Making phone calls", "Attending meetings only"], 0, "Telecommuting uses ICT to work remotely."),
("Which of the following is a spreadsheet application?", ["Microsoft Excel", "Adobe Photoshop", "VLC Player", "Windows Explorer"], 0, "Excel is spreadsheet software; the others are graphics, media and file tools."),
("In a database, which object presents data in a formatted layout for printing?", ["Report", "Query", "Table", "Form"], 0, "Reports format and print database data."),
("Which of the following is used to enter data into a database interactively?", ["Form", "Report", "Query", "Sort"], 0, "Forms provide a user-friendly data entry interface."),
]
