# CSEC Biology practice questions (p13-p100)
# Format: (question, [4 options], answer_index, explanation)
QUESTIONS = [
("Which organelle is known as the 'powerhouse of the cell'?", ["Mitochondrion", "Nucleus", "Ribosome", "Golgi body"], 0, "Mitochondria carry out aerobic respiration, releasing energy (ATP)."),
("What is the function of the cell membrane?", ["Controls what enters and leaves the cell", "Produces proteins", "Stores genetic material", "Carries out photosynthesis"], 0, "The membrane is selectively permeable, controlling transport."),
("Which of the following is found only in plant cells?", ["Chloroplast", "Nucleus", "Mitochondrion", "Ribosome"], 0, "Chloroplasts contain chlorophyll and are unique to plant cells."),
("The process by which water moves across a selectively permeable membrane is:", ["osmosis", "diffusion", "active transport", "transpiration"], 0, "Osmosis is the movement of water from high to low water potential across a membrane."),
("Which gas is taken in during photosynthesis?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], 0, "Plants take in CO₂ and release oxygen during photosynthesis."),
("The green pigment in leaves that absorbs light energy is:", ["chlorophyll", "carotene", "xanthophyll", "haemoglobin"], 0, "Chlorophyll absorbs light, mainly red and blue wavelengths."),
("What is the main product of photosynthesis?", ["Glucose", "Carbon dioxide", "Water", "Starch only"], 0, "Glucose is the primary carbohydrate produced; it may be stored as starch."),
("Which organelle is the site of protein synthesis?", ["Ribosome", "Mitochondrion", "Chloroplast", "Nucleus"], 0, "Ribosomes assemble amino acids into proteins."),
("The movement of molecules from high to low concentration without energy is:", ["diffusion", "osmosis only", "active transport", "translocation"], 0, "Diffusion is passive movement down a concentration gradient."),
("Which type of cell division produces gametes?", ["Meiosis", "Mitosis", "Binary fission", "Budding"], 0, "Meiosis halves the chromosome number to produce gametes."),
("Human body cells normally contain how many chromosomes?", ["46", "23", "92", "44"], 0, "Humans have 23 pairs = 46 chromosomes in body cells."),
("What is the function of red blood cells?", ["Transport oxygen", "Fight infection", "Clot blood", "Produce antibodies"], 0, "Haemoglobin in red blood cells carries oxygen."),
("Which blood vessel carries blood away from the heart?", ["Artery", "Vein", "Capillary", "Venule"], 0, "Arteries carry blood away from the heart."),
("The exchange of gases in the lungs occurs in the:", ["alveoli", "bronchi", "trachea", "diaphragm"], 0, "Alveoli are thin-walled air sacs where gas exchange happens."),
("What is the function of the small intestine?", ["Absorption of digested food", "Digestion of proteins only", "Storage of faeces", "Production of bile"], 0, "Villi in the small intestine absorb digested nutrients."),
("Which enzyme breaks down starch?", ["Amylase", "Protease", "Lipase", "Pepsin"], 0, "Amylase catalyses starch → maltose."),
("Bile is produced by the:", ["liver", "gall bladder", "pancreas", "stomach"], 0, "The liver produces bile; the gall bladder stores it."),
("Which of the following is a vitamin?", ["Vitamin C", "Calcium", "Iron", "Protein"], 0, "Vitamin C is a vitamin; calcium and iron are minerals; protein is a nutrient."),
("A deficiency of iron causes:", ["anaemia", "scurvy", "rickets", "goitre"], 0, "Iron is needed for haemoglobin; deficiency causes anaemia."),
("Which nutrient provides the most energy per gram?", ["Fats", "Carbohydrates", "Proteins", "Vitamins"], 0, "Fats provide about 37 kJ/g, more than carbohydrates or proteins."),
("What is the role of dietary fibre?", ["Helps prevent constipation", "Provides energy", "Builds muscle", "Transports oxygen"], 0, "Fibre adds bulk, aiding bowel movement and preventing constipation."),
("Which organ filters waste from the blood to form urine?", ["Kidney", "Liver", "Lungs", "Spleen"], 0, "The kidneys filter blood and produce urine."),
("The functional unit of the kidney is the:", ["nephron", "neuron", "alveolus", "glomerulus"], 0, "Nephrons filter blood and reabsorb useful substances."),
("Which hormone regulates blood sugar level?", ["Insulin", "Adrenaline", "Thyroxine", "Oestrogen"], 0, "Insulin lowers blood glucose; glucagon raises it."),
("Diabetes mellitus results from insufficient:", ["insulin", "thyroxine", "adrenaline", "growth hormone"], 0, "Type 1 diabetes is due to lack of insulin production."),
("Which part of the brain controls balance and coordination?", ["Cerebellum", "Cerebrum", "Medulla", "Hypothalamus"], 0, "The cerebellum coordinates movement and balance."),
("The basic unit of the nervous system is the:", ["neuron", "nephron", "axon", "synapse"], 0, "Neurons transmit nerve impulses."),
("Which disease is caused by a virus?", ["Influenza", "Cholera", "Tuberculosis", "Typhoid"], 0, "Influenza (flu) is viral; the others are bacterial."),
("Which disease is transmitted by the Aedes aegypti mosquito?", ["Dengue fever", "Malaria", "Cholera", "Tuberculosis"], 0, "Aedes aegypti transmits dengue; malaria is spread by Anopheles."),
("The body's first line of defence against pathogens is:", ["the skin", "white blood cells", "antibodies", "vaccination"], 0, "Skin acts as a physical barrier."),
("Vaccination provides immunity by:", ["stimulating antibody production", "killing all bacteria", "blocking all viruses", "reducing body temperature"], 0, "Vaccines introduce antigens that trigger antibody production."),
("Which white blood cell engulfs pathogens?", ["Phagocyte", "Lymphocyte", "Platelet", "Erythrocyte"], 0, "Phagocytes engulf and destroy pathogens by phagocytosis."),
("Antibodies are produced by:", ["lymphocytes", "phagocytes", "platelets", "red blood cells"], 0, "Lymphocytes produce antibodies against specific antigens."),
("Which is a non-communicable disease?", ["Heart disease", "Measles", "Chickenpox", "Malaria"], 0, "Heart disease is not transmitted from person to person."),
("What is the main cause of malaria?", ["Plasmodium protozoan", "Virus", "Bacterium", "Fungus"], 0, "Malaria is caused by the Plasmodium protozoan, spread by mosquitoes."),
("Which of the following is a symptom of cholera?", ["Severe diarrhoea", "Skin rash", "Coughing", "Fever with rash"], 0, "Cholera causes severe watery diarrhoea leading to dehydration."),
("The safest method to prevent the spread of HIV is:", ["abstinence or protected sex", "sharing needles", "blood transfusion without screening", "close hugging"], 0, "HIV spreads via body fluids; abstinence or protection prevents transmission."),
("What is a balanced diet?", ["A diet containing all nutrients in correct proportions", "A diet with only vegetables", "A diet high in protein", "A diet with no fats"], 0, "A balanced diet provides all nutrients in the right amounts."),
("Which vitamin is produced by the skin in sunlight?", ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin B12"], 0, "Sunlight converts a cholesterol derivative to vitamin D."),
("Scurvy is caused by a deficiency of:", ["Vitamin C", "Vitamin A", "Vitamin D", "Iron"], 0, "Vitamin C deficiency causes scurvy (bleeding gums, weakness)."),
("Which mineral is needed for strong bones and teeth?", ["Calcium", "Iron", "Sodium", "Potassium"], 0, "Calcium and phosphorus strengthen bones and teeth."),
("What is the function of the large intestine?", ["Absorption of water", "Absorption of glucose", "Digestion of proteins", "Production of enzymes"], 0, "The colon absorbs water and salts from undigested food."),
("Peristalsis refers to:", ["wave-like muscle contractions moving food", "the chewing of food", "the breakdown of food by acid", "the absorption of nutrients"], 0, "Peristalsis propels food along the alimentary canal."),
("Which part of the digestive system produces pepsin?", ["Stomach", "Mouth", "Small intestine", "Pancreas"], 0, "Gastric glands in the stomach secrete pepsin."),
("The function of the pancreas includes:", ["producing digestive enzymes and insulin", "storing bile", "absorbing water", "producing urine"], 0, "The pancreas secretes enzymes into the duodenum and insulin into blood."),
("Which is an example of a reflex action?", ["Pulling your hand away from a hot object", "Walking", "Reading", "Breathing deeply on purpose"], 0, "Reflexes are automatic, rapid responses to stimuli."),
("The sensory receptors in the eye that detect colour are:", ["cones", "rods", "lens cells", "optic nerves"], 0, "Cone cells detect colour; rods detect light intensity."),
("What is the function of the iris?", ["Controls the amount of light entering the eye", "Focuses light on the retina", "Transmits impulses to the brain", "Produces tears"], 0, "The iris adjusts pupil size to control light entry."),
("Which hormone is responsible for the 'fight or flight' response?", ["Adrenaline", "Insulin", "Thyroxine", "Progesterone"], 0, "Adrenaline prepares the body for emergency action."),
("Growth in plants is controlled by:", ["auxins", "insulin", "adrenaline", "glucagon"], 0, "Auxins regulate plant growth, e.g. phototropism."),
("The male sex cell in plants is found in:", ["pollen grains", "ovules", "sepals", "petals"], 0, "Pollen grains carry the male gametes."),
("Fertilisation in flowering plants occurs when:", ["the pollen tube fuses with the ovule", "the seed germinates", "the flower opens", "the fruit ripens"], 0, "The male gamete travels via the pollen tube to fuse with the ovule."),
("Which is an example of asexual reproduction?", ["Budding in yeast", "Fertilisation in humans", "Pollination in plants", "Egg and sperm fusion"], 0, "Budding produces offspring from one parent without gametes."),
("The structure where a fetus develops is the:", ["uterus", "ovary", "fallopian tube", "vagina"], 0, "The fetus develops in the uterus."),
("Which part of the male reproductive system produces sperm?", ["Testes", "Penis", "Prostate gland", "Urethra"], 0, "Sperm are produced in the seminiferous tubules of the testes."),
("The placenta functions to:", ["exchange nutrients and waste between mother and fetus", "produce eggs", "store urine", "produce sperm"], 0, "The placenta allows diffusion of oxygen and nutrients to the fetus."),
("A child's sex is determined by:", ["the father's sperm chromosome", "the mother's egg chromosome", "both parents equally", "the environment"], 0, "Sperm carrying X or Y determines sex; egg always carries X."),
("Genes are located on:", ["chromosomes", "ribosomes", "mitochondria", "cell walls"], 0, "Genes are segments of DNA on chromosomes."),
("Which is a dominant trait in humans?", ["Brown eyes", "Blue eyes", "Straight hair", "Attached earlobes"], 0, "Brown eye colour is dominant over blue."),
("If both parents are heterozygous (Bb) for a trait, the chance of a homozygous recessive (bb) child is:", ["25%", "50%", "75%", "100%"], 0, "Bb × Bb → BB, Bb, Bb, bb → 1/4 = 25%."),
("The observable characteristics of an organism are its:", ["phenotype", "genotype", "chromosome", "allele"], 0, "Phenotype is the physical expression of genes."),
("Which of the following is an example of a decomposer?", ["Fungus", "Grass", "Rabbit", "Hawk"], 0, "Fungi and bacteria break down dead organic matter."),
("The original source of energy for most food chains is:", ["the sun", "plants", "soil", "water"], 0, "Sunlight is captured by producers in photosynthesis."),
("In a food chain, the trophic level with the most energy is:", ["producers", "primary consumers", "secondary consumers", "tertiary consumers"], 0, "Energy decreases along the chain; producers have most."),
("What is the role of nitrogen-fixing bacteria?", ["Convert nitrogen gas to nitrates", "Release nitrogen to the air", "Produce oxygen", "Decompose proteins only"], 0, "They convert atmospheric nitrogen into usable nitrates."),
("Eutrophication of rivers is mainly caused by:", ["excess fertilisers in run-off", "acid rain", "oil spills", "deforestation only"], 0, "Nitrates and phosphates from fertilisers cause algal blooms."),
("Which gas is a major contributor to the greenhouse effect?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"], 0, "CO₂ traps heat in the atmosphere."),
("The removal of trees from a large area is called:", ["deforestation", "afforestation", "desertification", "conservation"], 0, "Deforestation is the clearing of forests."),
("Which is a renewable energy source?", ["Solar energy", "Coal", "Oil", "Natural gas"], 0, "Solar energy is replenished naturally."),
("A food web differs from a food chain because it:", ["shows multiple interconnected food chains", "shows only one pathway", "has no producers", "excludes consumers"], 0, "Food webs show complex feeding relationships."),
("The process of transpiration is important for:", ["water and mineral transport in plants", "photosynthesis only", "seed germination", "flower colour"], 0, "Transpiration pulls water up the xylem."),
("Which tissue transports water in plants?", ["Xylem", "Phloem", "Epidermis", "Cortex"], 0, "Xylem transports water and minerals upward."),
("Phloem transports:", ["sucrose and amino acids", "water only", "oxygen", "carbon dioxide"], 0, "Phloem transports organic solutes (translocation)."),
("What is the main function of the root hair cell?", ["Increase surface area for water absorption", "Photosynthesis", "Storage of starch", "Reproduction"], 0, "Root hairs greatly increase absorption surface area."),
("Which of these is a characteristic of living things?", ["Respiration", "Density", "Hardness", "Conductivity"], 0, "Respiration releases energy and is a life process."),
("The scientific name of humans is Homo sapiens. 'Homo' is the:", ["genus", "species", "family", "kingdom"], 0, "Binomial nomenclature: genus + species."),
("A microscope magnifies an object 400 times. If the objective lens is 40×, the eyepiece is:", ["10×", "4×", "100×", "440×"], 0, "Total = eyepiece × objective → 400/40 = 10×."),
("Which is the correct order of biological classification?", ["Kingdom, Phylum, Class, Order, Family, Genus, Species", "Species, Genus, Family, Order, Class, Phylum, Kingdom", "Kingdom, Class, Phylum, Order, Family, Genus, Species", "Family, Order, Class, Phylum, Kingdom, Genus, Species"], 0, "Memory aid: King Philip Came Over For Good Soup."),
("A plant cell placed in a concentrated salt solution will:", ["lose water and become flaccid", "gain water and swell", "remain unchanged", "burst"], 0, "Water leaves the cell by osmosis into the salt solution."),
("Turgor pressure in plant cells results from:", ["water entering the vacuole", "water leaving the cell", "cell wall dissolving", "chlorophyll production"], 0, "Water pushes against the cell wall, keeping the plant firm."),
("Which blood component helps clot blood at wounds?", ["Platelets", "Red blood cells", "White blood cells", "Plasma"], 0, "Platelets trigger clotting."),
("Plasma is mainly composed of:", ["water", "protein", "fat", "glucose"], 0, "Plasma is about 90% water carrying dissolved substances."),
("The heartbeat is controlled by the:", ["pacemaker", "valves", "aorta", "coronary artery"], 0, "The sinoatrial node (pacemaker) initiates each heartbeat."),
("Which lifestyle choice most reduces the risk of heart disease?", ["Regular exercise and balanced diet", "Smoking", "High-fat diet", "Sedentary lifestyle"], 0, "Exercise and diet lower cholesterol and blood pressure."),
("What is the function of the epiglottis?", ["Prevents food from entering the trachea", "Produces saliva", "Grinds food", "Absorbs water"], 0, "The epiglottis closes over the trachea during swallowing."),
("Breathing rate increases during exercise because:", ["more oxygen is needed for respiration", "muscles need less energy", "carbon dioxide decreases", "the heart slows down"], 0, "Muscles respire faster, needing more oxygen and removing more CO₂."),
("Which of the following reduces air pollution?", ["Using catalytic converters in cars", "Burning more fossil fuels", "Cutting down forests", "Using leaded petrol"], 0, "Catalytic converters reduce harmful exhaust gases."),
("Which of the following is an example of a habitat?", ["A mangrove swamp", "A species", "A population", "An organism"], 0, "A habitat is the natural home of an organism."),
]
