# CSEC Human & Social Biology practice questions (p13-p100)
# Format: (question, [4 options], answer_index, explanation)
QUESTIONS = [
("Which of the following is a function of the skeleton?", ["Support and protection of organs", "Producing urine", "Digesting food", "Carrying oxygen"], 0, "The skeleton supports the body and protects organs like the brain and heart."),
("The point where two bones meet is called a:", ["joint", "ligament", "muscle", "tendon"], 0, "Joints connect bones, allowing movement."),
("Which structure connects bone to bone?", ["Ligament", "Tendon", "Cartilage", "Muscle"], 0, "Ligaments hold bones together at joints."),
("A tendon connects:", ["muscle to bone", "bone to bone", "muscle to muscle", "nerve to bone"], 0, "Tendons attach muscles to bones."),
("Which type of muscle is found in the heart?", ["Cardiac muscle", "Skeletal muscle", "Smooth muscle", "Voluntary muscle"], 0, "Cardiac muscle pumps blood involuntarily."),
("When the biceps contracts, the arm:", ["bends (flexes)", "straightens", "lifts sideways", "remains still"], 0, "The biceps is a flexor, bending the elbow."),
("The triceps is responsible for:", ["straightening the arm", "bending the arm", "rotating the wrist", "moving the fingers"], 0, "The triceps is an extensor, straightening the elbow."),
("Red blood cells are produced in the:", ["bone marrow", "liver", "spleen", "kidney"], 0, "Bone marrow produces red blood cells (erythropoiesis)."),
("Which blood vessel has valves?", ["Vein", "Artery", "Capillary", "Aorta"], 0, "Veins have valves preventing backflow of blood."),
("Blood flows from the right ventricle to the:", ["lungs", "aorta", "left atrium", "brain"], 0, "The right ventricle pumps deoxygenated blood to the lungs."),
("The structure that prevents blood flowing back into the heart is the:", ["valve", "artery", "capillary", "septum"], 0, "Heart valves ensure one-way blood flow."),
("Which blood component transports carbon dioxide?", ["Plasma", "Platelets", "White blood cells", "Haemoglobin only"], 0, "Plasma carries CO₂ dissolved as bicarbonate."),
("The pulse is caused by:", ["the expansion of arteries as blood is pumped", "muscle contraction", "breathing", "nerve impulses"], 0, "Each heartbeat creates a pressure wave in arteries."),
("Which is the correct path of blood through the heart?", ["Right atrium → right ventricle → lungs → left atrium → left ventricle → body", "Left atrium → right atrium → lungs → body", "Right ventricle → left ventricle → lungs", "Lungs → right ventricle → body"], 0, "Deoxygenated blood goes to lungs, then oxygenated blood circulates."),
("What is the function of haemoglobin?", ["Carries oxygen", "Clots blood", "Fights infection", "Produces hormones"], 0, "Haemoglobin binds oxygen in red blood cells."),
("The walls of which blood vessel are only one cell thick?", ["Capillary", "Artery", "Vein", "Venule"], 0, "Capillary walls allow exchange of substances."),
("Breathing in is called:", ["inhalation", "exhalation", "respiration", "ventilation only"], 0, "Inhalation draws air into the lungs."),
("The dome-shaped muscle below the lungs is the:", ["diaphragm", "pleura", "trachea", "larynx"], 0, "The diaphragm aids breathing by contracting and relaxing."),
("Which of the following increases the rate of breathing?", ["Exercise", "Sleeping", "Sitting still", "Meditation"], 0, "Exercise raises oxygen demand and CO₂ production."),
("Gaseous exchange in the lungs occurs by:", ["diffusion", "osmosis", "active transport", "filtration"], 0, "Oxygen and CO₂ diffuse across alveolar walls."),
("Which of the following is a product of anaerobic respiration in muscles?", ["Lactic acid", "Ethanol", "Carbon dioxide only", "Water"], 0, "Muscles produce lactic acid during anaerobic respiration."),
("Aerobic respiration releases energy from glucose using:", ["oxygen", "nitrogen", "carbon dioxide", "hydrogen"], 0, "Aerobic respiration requires oxygen."),
("The chemical equation for aerobic respiration is:", ["Glucose + Oxygen → Carbon dioxide + Water + Energy", "Glucose → Lactic acid + Energy", "Carbon dioxide + Water → Glucose + Oxygen", "Glucose + Water → Energy"], 0, "Glucose and oxygen yield CO₂, water and energy."),
("Which organ removes urea from the blood?", ["Kidney", "Lung", "Heart", "Stomach"], 0, "The kidneys filter urea and excrete it in urine."),
("Urea is produced in the:", ["liver", "kidney", "bladder", "pancreas"], 0, "The liver deaminates amino acids, producing urea."),
("Which of the following is NOT excreted by the body?", ["Glucose", "Urea", "Carbon dioxide", "Water"], 0, "Glucose is normally reabsorbed, not excreted."),
("The tube connecting the kidney to the bladder is the:", ["ureter", "urethra", "nephron", "aorta"], 0, "Ureters carry urine from kidneys to bladder."),
("Urine leaves the body through the:", ["urethra", "ureter", "kidney", "bladder"], 0, "The urethra carries urine out of the body."),
("Sweating helps regulate body temperature by:", ["evaporation cooling the skin", "producing heat", "storing water", "increasing blood flow only"], 0, "Evaporating sweat removes heat energy."),
("Which gland produces insulin?", ["Pancreas", "Thyroid", "Adrenal", "Pituitary"], 0, "The pancreas secretes insulin."),
("Insulin lowers blood glucose by:", ["converting glucose to glycogen", "releasing more sugar", "stopping glucose absorption", "increasing appetite"], 0, "Insulin promotes glycogen storage, lowering blood sugar."),
("A deficiency of thyroxine can cause:", ["slow metabolism", "rapid growth", "diabetes", "anaemia"], 0, "Thyroxine controls metabolic rate."),
("Growth hormone is produced by the:", ["pituitary gland", "pancreas", "adrenal gland", "thyroid"], 0, "The pituitary gland secretes growth hormone."),
("Which of the following is a sense organ?", ["Ear", "Kidney", "Liver", "Pancreas"], 0, "The ear detects sound (sensory organ)."),
("The retina of the eye contains:", ["light-sensitive cells", "bone cells", "sweat glands", "hair cells"], 0, "Rods and cones in the retina detect light."),
("The lens of the eye focuses light onto the:", ["retina", "iris", "cornea", "pupil"], 0, "The lens refracts light to focus on the retina."),
("Which part of the ear converts vibrations into nerve impulses?", ["Cochlea", "Eardrum", "Pinna", "Ear canal"], 0, "The cochlea contains hair cells that generate impulses."),
("The sense of taste is detected by:", ["taste buds on the tongue", "the nose", "the ears", "the skin"], 0, "Taste buds on the tongue detect chemicals in food."),
("Which of the following is a stimulant?", ["Caffeine", "Alcohol", "Marijuana", "Paracetamol"], 0, "Caffeine speeds up the nervous system."),
("Alcohol abuse can cause:", ["liver damage", "better memory", "stronger bones", "healthier lungs"], 0, "Alcohol damages the liver (cirrhosis)."),
("Smoking tobacco increases the risk of:", ["lung cancer", "diabetes only", "anaemia", "goitre"], 0, "Cigarette smoke contains carcinogens causing lung cancer."),
("Which drug is used as a pain reliever?", ["Aspirin", "Cocaine", "Heroin", "Nicotine"], 0, "Aspirin is an analgesic (pain reliever)."),
("Drug addiction is best described as:", ["a physical and psychological dependence on a drug", "occasional use", "prescribed medicine", "a healthy habit"], 0, "Addiction involves compulsive drug use despite harm."),
("Which of the following is a communicable disease?", ["Influenza", "Heart disease", "Cancer", "Diabetes"], 0, "Influenza spreads from person to person."),
("Tuberculosis (TB) mainly affects the:", ["lungs", "kidneys", "skin", "brain"], 0, "TB is a bacterial infection of the lungs."),
("Cholera is spread mainly through:", ["contaminated water and food", "mosquito bites", "the air", "blood transfusion"], 0, "Cholera bacteria spread via faecal-oral contamination."),
("Which disease is transmitted by the Aedes mosquito?", ["Dengue fever", "Cholera", "Tuberculosis", "Measles"], 0, "Aedes aegypti transmits dengue."),
("Malaria is caused by a:", ["protozoan", "virus", "bacterium", "fungus"], 0, "Plasmodium, a protozoan, causes malaria."),
("Which of the following is a barrier method of contraception?", ["Condom", "Pill", "Injection", "Implant"], 0, "Condoms physically block sperm."),
("The contraceptive pill works by:", ["preventing ovulation", "killing sperm", "blocking the uterus", "increasing sperm count"], 0, "Hormonal pills inhibit ovulation."),
("Which contraceptive also protects against STIs?", ["Condom", "Pill", "IUD", "Vasectomy"], 0, "Condoms prevent STI transmission."),
("HIV attacks which type of cells?", ["White blood cells (lymphocytes)", "Red blood cells", "Platelets", "Bone cells"], 0, "HIV destroys helper T-lymphocytes, weakening immunity."),
("HIV can be transmitted through:", ["unprotected sexual intercourse", "sharing meals", "hugging", "mosquito bites"], 0, "HIV spreads via body fluids like blood and semen."),
("A person with AIDS has:", ["a severely weakened immune system", "extra immunity", "no symptoms ever", "stronger bones"], 0, "AIDS is the advanced stage of HIV infection."),
("Which of the following is a non-communicable disease?", ["Diabetes", "Measles", "Chickenpox", "Malaria"], 0, "Diabetes is not transmitted between people."),
("Obesity increases the risk of:", ["heart disease", "cholera", "malaria", "flu"], 0, "Obesity is linked to hypertension and heart disease."),
("Which of the following helps prevent heart disease?", ["Regular exercise", "Smoking", "High-fat diet", "Stress"], 0, "Exercise strengthens the heart and lowers blood pressure."),
("Hypertension means:", ["high blood pressure", "low blood sugar", "fast breathing", "weak bones"], 0, "Hypertension is chronically elevated blood pressure."),
("A balanced diet should contain:", ["all nutrients in correct proportions", "only carbohydrates", "only proteins", "no fats"], 0, "Balance means adequate carbohydrates, proteins, fats, vitamins and minerals."),
("Which nutrient is the body's main source of energy?", ["Carbohydrates", "Proteins", "Vitamins", "Minerals"], 0, "Carbohydrates provide readily available energy."),
("Proteins are essential for:", ["growth and repair of tissues", "storing energy only", "cooling the body", "digesting fats"], 0, "Proteins build and repair body cells."),
("Which vitamin prevents night blindness?", ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B12"], 0, "Vitamin A is needed for vision in dim light."),
("A deficiency of Vitamin D causes:", ["rickets", "scurvy", "anaemia", "goitre"], 0, "Vitamin D deficiency causes rickets (soft bones)."),
("Which mineral prevents goitre?", ["Iodine", "Iron", "Calcium", "Sodium"], 0, "Iodine is needed for thyroxine production."),
("Iron deficiency causes:", ["anaemia", "scurvy", "rickets", "night blindness"], 0, "Iron is needed to make haemoglobin."),
("Kwashiorkor is caused by a deficiency of:", ["protein", "carbohydrates", "vitamin C", "calcium"], 0, "Kwashiorkor is severe protein deficiency."),
("Which of the following is a symptom of marasmus?", ["Severe wasting from energy deficiency", "Bleeding gums", "Soft bones", "Swollen joints"], 0, "Marasmus results from severe calorie deficiency."),
("The process of breaking down food into soluble substances is:", ["digestion", "absorption", "egestion", "respiration"], 0, "Digestion breaks food into absorbable molecules."),
("Saliva contains which enzyme?", ["Amylase", "Pepsin", "Lipase", "Trypsin"], 0, "Salivary amylase digests starch."),
("Pepsin digests:", ["proteins", "carbohydrates", "fats", "fibre"], 0, "Pepsin breaks proteins into peptides in the stomach."),
("Bile helps in the digestion of:", ["fats", "proteins", "starch", "minerals"], 0, "Bile emulsifies fats, aiding lipase action."),
("The small intestine is adapted for absorption by:", ["villi", "acid", "teeth", "peristalsis only"], 0, "Villi increase surface area for absorption."),
("Which of the following is absorbed directly into the bloodstream?", ["Glucose", "Starch", "Cellulose", "Fat droplets"], 0, "Glucose is absorbed into capillaries of villi."),
("Water is absorbed mainly in the:", ["large intestine", "stomach", "mouth", "oesophagus"], 0, "The colon absorbs water and minerals."),
("The appendix is attached to the:", ["large intestine", "stomach", "liver", "pancreas"], 0, "The appendix projects from the caecum of the large intestine."),
("Tooth decay is caused by:", ["bacteria acting on sugars", "chewing gum", "cold drinks only", "brushing too much"], 0, "Bacteria ferment sugars, producing acids that erode enamel."),
("Which of the following prevents tooth decay?", ["Fluoride in toothpaste", "Eating sweets", "Skipping brushing", "Drinking sugary drinks"], 0, "Fluoride strengthens enamel against acid."),
("Fertilisation in humans occurs in the:", ["fallopian tube", "uterus", "ovary", "vagina"], 0, "The egg is fertilised in the fallopian tube."),
("The placenta allows:", ["exchange of nutrients and wastes", "production of eggs", "urine storage", "sperm production"], 0, "The placenta exchanges oxygen, nutrients and wastes."),
("Puberty in girls begins with:", ["menstruation", "menopause", "pregnancy", "lactation"], 0, "Menarche (first menstruation) marks puberty onset."),
("The menstrual cycle is controlled by:", ["hormones", "nerves only", "blood pressure", "diet only"], 0, "Oestrogen and progesterone regulate the cycle."),
("The average duration of the menstrual cycle is:", ["28 days", "7 days", "40 days", "14 days"], 0, "The typical cycle is about 28 days."),
("Which of the following is a method of preventing pregnancy?", ["Contraception", "Exercise", "Dieting", "Vaccination"], 0, "Contraception prevents conception."),
("Sexually transmitted infections can be prevented by:", ["using condoms", "sharing needles", "multiple partners", "avoiding testing"], 0, "Condoms reduce STI transmission."),
("Which of the following is a public health measure?", ["Vaccination programmes", "Private gyms", "Personal cars", "Gated communities"], 0, "Vaccination protects whole communities."),
("Vaccination provides immunity by:", ["stimulating antibody production", "killing all germs instantly", "lowering body temperature", "increasing white cell count only"], 0, "Vaccines trigger the immune system to produce antibodies."),
("Herd immunity occurs when:", ["a large proportion of the population is immune", "everyone is sick", "no one is vaccinated", "hospitals close"], 0, "High vaccination rates protect the vulnerable."),
("Which of the following is a vector for disease?", ["Mosquito", "River", "Building", "Fruit"], 0, "Mosquitoes transmit malaria and dengue."),
("The safe disposal of faeces is important to prevent:", ["cholera", "cancer", "diabetes", "asthma"], 0, "Proper sanitation prevents faecal-oral diseases."),
("Which of the following is a greenhouse gas?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"], 0, "CO₂ traps heat, contributing to global warming."),
("Air pollution can cause:", ["respiratory diseases", "better lung function", "stronger immunity", "clearer skin"], 0, "Pollutants like smoke damage the respiratory system."),
]
