# CSEC Social Studies practice questions (p13-p100)
# Format: (question, [4 options], answer_index, explanation)
QUESTIONS = [
("The term 'society' refers to:", ["a group of people sharing a common culture and territory", "a political party", "a family only", "a building"], 0, "A society is a community of people with shared culture and institutions."),
("Which of the following is an example of a primary group?", ["Family", "Political party", "Trade union", "Church congregation"], 0, "Primary groups have close, personal relationships."),
("Socialisation is the process of:", ["learning the norms and values of society", "forming a government", "earning money", "moving house"], 0, "Socialisation teaches individuals society's expected behaviours."),
("Which agent of socialisation is most influential in early childhood?", ["The family", "The media", "The school", "Peer groups"], 0, "The family socialises children first and most intensely."),
("Norms are:", ["expected standards of behaviour", "laws passed by parliament", "religious beliefs only", "government policies"], 0, "Norms are unwritten rules guiding behaviour."),
("Values in a society are:", ["shared beliefs about what is important", "taxes paid", "types of housing", "political parties"], 0, "Values are collective ideas about what is good and desirable."),
("Social stratification refers to:", ["the division of society into layers or classes", "migration patterns", "the education system", "family structures"], 0, "Stratification ranks individuals into social classes."),
("Which of the following is a Caribbean family type?", ["Extended family", "Single-class family", "Nuclear party", "Government family"], 0, "Extended families (including grandparents, aunts etc.) are common in the Caribbean."),
("A 'common-law union' refers to:", ["a couple living together without formal marriage", "a legal partnership", "a type of adoption", "a church wedding"], 0, "Common-law unions are informal but recognised living arrangements."),
("Which institution is responsible for formal education?", ["School", "The media", "Peer groups", "Workplace"], 0, "Schools provide formal education."),
("The family's main economic function is to:", ["provide for members' basic needs", "create laws", "educate the nation", "collect taxes"], 0, "The family provides food, shelter and other needs."),
("A 'push factor' in migration is:", ["a condition that drives people away from a place", "a reason to stay", "a job offer abroad", "better schools"], 0, "Push factors (e.g. unemployment, war) drive emigration."),
("A 'pull factor' in migration is:", ["an attraction to a new destination", "a reason to leave", "a tax increase", "family separation"], 0, "Pull factors (e.g. jobs, freedom) attract migrants."),
("Brain drain refers to:", ["the emigration of skilled workers", "the loss of forests", "a type of disease", "poor education"], 0, "Brain drain is the loss of trained professionals to other countries."),
("Remittances are:", ["money sent home by migrants", "government grants", "tax refunds", "school fees"], 0, "Migrants send remittances to support families at home."),
("Which of the following is a Caribbean regional organisation?", ["CARICOM", "UNESCO", "NATO", "OPEC"], 0, "CARICOM is the Caribbean Community."),
("The main purpose of CARICOM is to:", ["promote economic integration and cooperation", "build roads", "organise sports", "collect taxes"], 0, "CARICOM fosters trade, cooperation and integration."),
("Which CARICOM organ is the highest decision-making body?", ["The Conference of Heads of Government", "The Secretariat", "The Court of Justice", "The Assembly"], 0, "Heads of Government set CARICOM policy."),
("The CARICOM Single Market and Economy (CSME) allows:", ["free movement of goods, services, capital and labour", "only free movement of goods", "military alliances", "currency unification only"], 0, "CSME deepens the single market for factors of production."),
("The Caribbean Court of Justice (CCJ) functions as:", ["the final court of appeal and an international tribunal", "a trade union", "a development bank", "a university"], 0, "The CCJ is the region's final appellate court and interprets the treaty."),
("Which of the following is an example of a regional institution?", ["University of the West Indies", "United Nations", "World Bank", "IMF"], 0, "The UWI serves Caribbean tertiary education regionally."),
("A constitution is:", ["the supreme law that sets out how a country is governed", "a political party", "a trade agreement", "a census"], 0, "The constitution establishes the framework of government."),
("Which branch of government makes laws?", ["The legislature", "The executive", "The judiciary", "The civil service"], 0, "Parliament (legislature) enacts laws."),
("The executive branch of government:", ["implements and administers laws", "interprets laws", "passes laws", "holds elections"], 0, "The executive (PM and Cabinet) carries out laws."),
("The judiciary's role is to:", ["interpret and apply the law", "make laws", "collect taxes", "print money"], 0, "Courts interpret laws and settle disputes."),
("In a parliamentary democracy, the Head of Government is usually the:", ["Prime Minister", "President only", "Chief Justice", "Speaker"], 0, "The PM leads the government in parliamentary systems."),
("The electoral system in most Caribbean countries is:", ["first-past-the-post", "proportional representation only", "dictatorship", "hereditary succession"], 0, "Candidates with the most votes in each constituency win."),
("A 'constituency' is:", ["an electoral area that elects a representative", "a political party", "a government department", "a court"], 0, "Constituencies elect members of parliament."),
("The opposition in Parliament:", ["monitors and challenges the government", "passes all laws", "appoints judges", "controls the civil service"], 0, "The opposition scrutinises government actions."),
("Universal adult suffrage means:", ["all adult citizens can vote", "only property owners vote", "men only vote", "the government chooses voters"], 0, "Every adult citizen has the right to vote."),
("Citizenship rights include the right to:", ["vote and protection under the law", "ignore taxes", "break laws", "refuse education"], 0, "Citizens enjoy political and legal rights."),
("A responsibility of citizens is to:", ["pay taxes", "avoid work", "only claim rights", "ignore elections"], 0, "Citizens contribute by paying taxes and obeying laws."),
("Which of the following is a civic responsibility?", ["Voting in elections", "Buying imported goods", "Going on vacation", "Watching television"], 0, "Voting is a key civic duty in a democracy."),
("'Rule of law' means:", ["everyone is subject to the law", "only citizens obey the law", "police make laws", "judges elect governments"], 0, "The law applies equally to all, including leaders."),
("The public service is responsible for:", ["implementing government policies", "making laws", "judging cases", "campaigning for parties"], 0, "Civil servants administer policies and services."),
("Sustainable development means:", ["meeting present needs without harming future generations", "using resources as fast as possible", "reducing population", "building more factories"], 0, "Sustainability balances development with resource conservation."),
("Which of the following is a sustainable practice?", ["Solar energy use", "Deforestation", "Overfishing", "Burning fossil fuels"], 0, "Renewable energy conserves resources."),
("The 'greenhouse effect' is caused by:", ["greenhouse gases trapping heat", "recycling", "wind power", "planting trees"], 0, "CO₂ and other gases trap heat in the atmosphere."),
("Global warming is mainly caused by:", ["increased greenhouse gas emissions", "more rainfall", "longer school days", "cheaper food"], 0, "Human emissions of CO₂ drive global warming."),
("Which organisation promotes sustainable development globally?", ["United Nations", "CARICOM only", "The IMF", "OPEC"], 0, "The UN coordinates global sustainability goals."),
("The population of a country is studied through the:", ["census", "budget", "constitution", "referendum"], 0, "A census counts and profiles the population."),
("The birth rate is:", ["the number of live births per 1,000 people per year", "the number of babies in hospitals", "the population growth", "the death rate"], 0, "Crude birth rate measures births per 1,000 population."),
("If the birth rate exceeds the death rate, the population:", ["increases naturally", "decreases", "stays constant", "doubles always"], 0, "Natural increase = births - deaths."),
("The 'dependency ratio' compares:", ["dependents to the working-age population", "births to deaths", "men to women", "urban to rural population"], 0, "It measures the burden on the productive population."),
("Which of the following is a 'push' factor for rural-urban migration?", ["Lack of jobs in rural areas", "Better housing in rural areas", "Lower food prices", "More land"], 0, "Unemployment pushes rural residents to cities."),
("Urbanisation refers to:", ["the growth of towns and cities", "a decline in farming", "the spread of forests", "lower birth rates"], 0, "Urbanisation is increasing urban population."),
("Which of the following is a consequence of urbanisation?", ["Housing shortages", "More farmland", "Fewer cars", "Lower crime"], 0, "Rapid urban growth strains housing and services."),
("A 'primary industry' is one that:", ["extracts raw materials", "manufactures goods", "provides services", "sells products"], 0, "Farming, fishing and mining are primary industries."),
("Which of the following is a secondary industry?", ["Manufacturing", "Farming", "Banking", "Tourism"], 0, "Secondary industries process raw materials into goods."),
("Tourism is an example of a:", ["tertiary industry", "primary industry", "secondary industry", "extractive industry"], 0, "Tourism is a service (tertiary) industry."),
("Which of the following benefits does tourism bring to the Caribbean?", ["Foreign exchange earnings", "Fewer visitors", "Loss of jobs", "Higher unemployment"], 0, "Tourism earns foreign exchange and creates employment."),
("A disadvantage of tourism is:", ["environmental degradation", "more income", "job creation", "cultural exchange"], 0, "Tourism can damage beaches, reefs and ecosystems."),
("Consumer protection laws aim to:", ["protect buyers from unfair practices", "increase prices", "limit shopping", "tax imports"], 0, "They safeguard consumers' rights and safety."),
("The Consumer Protection Act gives consumers the right to:", ["safe goods and redress", "free goods", "ignore contracts", "avoid payment"], 0, "Consumers are entitled to safety, information and remedies."),
("A 'cooperative' is a business:", ["owned and run by its members", "owned by the state", "owned by shareholders only", "run by the government"], 0, "Cooperatives are member-owned and democratically run."),
("Which of the following is a Caribbean cooperative example?", ["Credit unions", "National banks", "Political parties", "Airports"], 0, "Credit unions are financial cooperatives."),
("The Caribbean Examination Council (CXC) is an example of:", ["regional cooperation in education", "a trade union", "a political party", "a central bank"], 0, "CXC coordinates regional examinations."),
("Which of the following is a communication technology?", ["The internet", "Farming", "Fishing", "Mining"], 0, "The internet enables global communication."),
("The 'digital divide' describes:", ["unequal access to technology", "computer repairs", "internet speed", "online shopping"], 0, "It separates those with and without ICT access."),
("Which of the following is an advantage of ICT in education?", ["Access to online resources", "More homework", "Expensive devices", "Less learning"], 0, "ICT expands learning materials and methods."),
("Globalisation refers to:", ["increasing global interconnectedness", "national isolation", "fewer imports", "local trade only"], 0, "Globalisation links economies, cultures and people worldwide."),
("Which of the following is an effect of globalisation?", ["Cultural exchange", "No trade", "Closed borders", "Fewer goods"], 0, "Globalisation spreads culture, goods and ideas."),
("A 'multinational corporation' is a company that:", ["operates in several countries", "operates in one town", "is state-owned", "employs only locals"], 0, "Multinationals have operations across borders."),
("Which of the following is an advantage of multinationals in the Caribbean?", ["Job creation", "Loss of culture always", "Higher pollution", "Profit outflow"], 0, "Multinationals create employment and transfer skills."),
("Environmental conservation means:", ["protecting natural resources", "using resources wastefully", "clearing forests", "overfishing"], 0, "Conservation manages resources sustainably."),
("Which of the following pollutes the environment?", ["Burning of waste", "Recycling", "Composting", "Solar power"], 0, "Burning waste releases harmful pollutants."),
("Reforestation is the:", ["planting of trees in deforested areas", "cutting of trees", "building of dams", "mining of land"], 0, "Reforestation restores forest cover."),
("Which of the following is a renewable resource?", ["Wind", "Oil", "Coal", "Natural gas"], 0, "Wind energy is naturally replenished."),
("Water pollution is mainly caused by:", ["industrial waste and sewage", "rainfall", "wind", "sunlight"], 0, "Effluents and sewage contaminate water bodies."),
("Which of the following is a consequence of water pollution?", ["Disease outbreaks", "More fish", "Clean beaches", "Better health"], 0, "Polluted water spreads waterborne diseases."),
("The term 'infrastructure' refers to:", ["basic facilities like roads, water and electricity", "school uniforms", "political parties", "bank accounts"], 0, "Infrastructure underpins economic activity."),
("Which of the following is a type of infrastructure?", ["Roads", "Textbooks", "Mobile phones", "Fertiliser"], 0, "Transport networks are physical infrastructure."),
("A 'budget' of a government is:", ["a plan of revenue and expenditure", "a law", "a tax", "a census"], 0, "Budgets allocate government income and spending."),
("Which of the following is a source of government revenue?", ["Taxes", "Loans only", "Exports only", "Imports"], 0, "Taxes fund most government services."),
("Direct taxes are those paid:", ["directly on income and wealth", "on goods at purchase", "by importers only", "by tourists only"], 0, "Income tax is a direct tax."),
("Indirect taxes include:", ["Value Added Tax (VAT)", "Income tax", "Property tax", "Corporate tax"], 0, "VAT is charged on goods and services."),
("The 'informal sector' refers to:", ["economic activity not formally registered", "government jobs", "large factories", "export industries"], 0, "Informal work (e.g. street vending) is unregistered."),
("Which of the following is an example of the informal sector?", ["Street vendor", "Bank teller", "Teacher", "Civil servant"], 0, "Street vending is typically informal."),
("Unemployment means:", ["people able and willing to work but without jobs", "people not in school", "retired workers", "tourists"], 0, "Unemployment excludes those not seeking work."),
("Which of the following reduces unemployment?", ["Job training programmes", "Closing businesses", "Fewer schools", "Higher taxes"], 0, "Training improves employability."),
("Poverty is best defined as:", ["lack of basic needs like food and shelter", "low income only", "being unemployed", "living in rural areas"], 0, "Poverty is the inability to meet basic needs."),
("Which of the following is a cause of poverty?", ["Low education levels", "High wages", "Good healthcare", "Cheap food"], 0, "Limited education limits earning opportunities."),
("A 'welfare state' provides:", ["social services to citizens", "only defence", "only roads", "no services"], 0, "Welfare states offer health, education and social security."),
("Which of the following is a social service?", ["Healthcare", "Roads", "Ports", "Airports"], 0, "Health and education are social services."),
("The role of the teacher in socialisation is to:", ["transmit knowledge and values", "make laws", "collect taxes", "judge criminals"], 0, "Schools socialise children through curricula and values."),
("Peer groups influence adolescents mainly through:", ["shared values and pressure", "legal enforcement", "taxation", "military service"], 0, "Peers shape attitudes, styles and behaviours."),
("The media's influence on society includes:", ["shaping public opinion", "collecting taxes", "building roads", "holding elections"], 0, "Media inform and influence attitudes and values."),
("Which of the following is an example of mass media?", ["Television", "A diary", "A letter", "A phone call"], 0, "Television reaches large audiences."),
("Culture is defined as:", ["the shared beliefs, customs and arts of a group", "a political system", "the economy", "geography"], 0, "Culture includes language, religion, food and traditions."),
("Which of the following is part of material culture?", ["Food and clothing", "Beliefs", "Values", "Language"], 0, "Material culture includes physical objects."),
("Non-material culture includes:", ["beliefs and values", "buildings", "tools", "clothing"], 0, "Non-material culture is ideas and beliefs."),
]
